package jp.co.pds.PJ0002.dao.mapper;

import java.util.List;
import jp.co.pds.PJ0002.dao.dto.DtExpenseAdjstmnt;
import jp.co.pds.PJ0002.dao.dto.DtExpenseAdjstmntExample;
import org.apache.ibatis.annotations.Param;

public interface DtExpenseAdjstmntMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    long countByExample(DtExpenseAdjstmntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    int deleteByExample(DtExpenseAdjstmntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    int deleteByPrimaryKey(Integer expenseAdjstmntId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    int insert(DtExpenseAdjstmnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    int insertSelective(DtExpenseAdjstmnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    List<DtExpenseAdjstmnt> selectByExample(DtExpenseAdjstmntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    DtExpenseAdjstmnt selectByPrimaryKey(Integer expenseAdjstmntId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    int updateByExampleSelective(@Param("record") DtExpenseAdjstmnt record, @Param("example") DtExpenseAdjstmntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    int updateByExample(@Param("record") DtExpenseAdjstmnt record, @Param("example") DtExpenseAdjstmntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    int updateByPrimaryKeySelective(DtExpenseAdjstmnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    int updateByPrimaryKey(DtExpenseAdjstmnt record);
}