package jp.co.pds.PJ0002.dao.mapper;

import java.util.List;
import jp.co.pds.PJ0002.dao.dto.DtTransportExpense;
import jp.co.pds.PJ0002.dao.dto.DtTransportExpenseExample;
import org.apache.ibatis.annotations.Param;

public interface DtTransportExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    long countByExample(DtTransportExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    int deleteByExample(DtTransportExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    int deleteByPrimaryKey(Integer transportExpenseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    int insert(DtTransportExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    int insertSelective(DtTransportExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    List<DtTransportExpense> selectByExample(DtTransportExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    DtTransportExpense selectByPrimaryKey(Integer transportExpenseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    int updateByExampleSelective(@Param("record") DtTransportExpense record, @Param("example") DtTransportExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    int updateByExample(@Param("record") DtTransportExpense record, @Param("example") DtTransportExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    int updateByPrimaryKeySelective(DtTransportExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_transport_expense
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    int updateByPrimaryKey(DtTransportExpense record);
}