package jp.co.pds.PJ0002.dao.mapper;

import java.util.List;
import jp.co.pds.PJ0002.dao.dto.MsAccountTitle;
import jp.co.pds.PJ0002.dao.dto.MsAccountTitleExample;
import org.apache.ibatis.annotations.Param;

public interface MsAccountTitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    long countByExample(MsAccountTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int deleteByExample(MsAccountTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int deleteByPrimaryKey(Integer accountTitleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int insert(MsAccountTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int insertSelective(MsAccountTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    List<MsAccountTitle> selectByExample(MsAccountTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    MsAccountTitle selectByPrimaryKey(Integer accountTitleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int updateByExampleSelective(@Param("record") MsAccountTitle record, @Param("example") MsAccountTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int updateByExample(@Param("record") MsAccountTitle record, @Param("example") MsAccountTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int updateByPrimaryKeySelective(MsAccountTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int updateByPrimaryKey(MsAccountTitle record);
}