package jp.co.pds.PJ0002.dao.mapper;

import java.util.List;
import jp.co.pds.PJ0002.dao.dto.MsCompanyAccountTitle;
import jp.co.pds.PJ0002.dao.dto.MsCompanyAccountTitleExample;
import jp.co.pds.PJ0002.dao.dto.MsCompanyAccountTitleKey;
import org.apache.ibatis.annotations.Param;

public interface MsCompanyAccountTitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    long countByExample(MsCompanyAccountTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int deleteByExample(MsCompanyAccountTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int deleteByPrimaryKey(MsCompanyAccountTitleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int insert(MsCompanyAccountTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int insertSelective(MsCompanyAccountTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    List<MsCompanyAccountTitle> selectByExample(MsCompanyAccountTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    MsCompanyAccountTitle selectByPrimaryKey(MsCompanyAccountTitleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int updateByExampleSelective(@Param("record") MsCompanyAccountTitle record, @Param("example") MsCompanyAccountTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int updateByExample(@Param("record") MsCompanyAccountTitle record, @Param("example") MsCompanyAccountTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int updateByPrimaryKeySelective(MsCompanyAccountTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_account_title
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    int updateByPrimaryKey(MsCompanyAccountTitle record);
}