package jp.co.pds.PJ0002.dao.mapper;

import java.util.List;
import jp.co.pds.PJ0002.dao.dto.MsRestTime;
import jp.co.pds.PJ0002.dao.dto.MsRestTimeExample;
import org.apache.ibatis.annotations.Param;

public interface MsRestTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    long countByExample(MsRestTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int deleteByExample(MsRestTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int deleteByPrimaryKey(Integer restTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int insert(MsRestTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int insertSelective(MsRestTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    List<MsRestTime> selectByExample(MsRestTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    MsRestTime selectByPrimaryKey(Integer restTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int updateByExampleSelective(@Param("record") MsRestTime record, @Param("example") MsRestTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int updateByExample(@Param("record") MsRestTime record, @Param("example") MsRestTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int updateByPrimaryKeySelective(MsRestTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_rest_time
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int updateByPrimaryKey(MsRestTime record);
}