package jp.co.pds.PJ0001.dao.dto;

public class DtAnswerDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_answer_detail.ANSWER_ID
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    private Integer answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_answer_detail.QUESTION_ID
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    private Integer questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_answer_detail.ANSWER_ID
     *
     * @return the value of dt_answer_detail.ANSWER_ID
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_answer_detail.ANSWER_ID
     *
     * @param answerId the value for dt_answer_detail.ANSWER_ID
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_answer_detail.QUESTION_ID
     *
     * @return the value of dt_answer_detail.QUESTION_ID
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_answer_detail.QUESTION_ID
     *
     * @param questionId the value for dt_answer_detail.QUESTION_ID
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
}