package jp.co.pds.PJ0001.dao.dto;

public class MsGroupQuestionGroupKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group_question_group.GROUP_ID
     *
     * @mbg.generated Mon Mar 19 19:21:33 JST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group_question_group.QUESTION_GROUP_ID
     *
     * @mbg.generated Mon Mar 19 19:21:33 JST 2018
     */
    private Integer questionGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group_question_group.GROUP_ID
     *
     * @return the value of ms_group_question_group.GROUP_ID
     *
     * @mbg.generated Mon Mar 19 19:21:33 JST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group_question_group.GROUP_ID
     *
     * @param groupId the value for ms_group_question_group.GROUP_ID
     *
     * @mbg.generated Mon Mar 19 19:21:33 JST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group_question_group.QUESTION_GROUP_ID
     *
     * @return the value of ms_group_question_group.QUESTION_GROUP_ID
     *
     * @mbg.generated Mon Mar 19 19:21:33 JST 2018
     */
    public Integer getQuestionGroupId() {
        return questionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group_question_group.QUESTION_GROUP_ID
     *
     * @param questionGroupId the value for ms_group_question_group.QUESTION_GROUP_ID
     *
     * @mbg.generated Mon Mar 19 19:21:33 JST 2018
     */
    public void setQuestionGroupId(Integer questionGroupId) {
        this.questionGroupId = questionGroupId;
    }
}