package jp.co.pds.PJ0001.dao.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MsQuestionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public MsQuestionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("QUESTION_ID is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("QUESTION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Integer value) {
            addCriterion("QUESTION_ID =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Integer value) {
            addCriterion("QUESTION_ID <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Integer value) {
            addCriterion("QUESTION_ID >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("QUESTION_ID >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Integer value) {
            addCriterion("QUESTION_ID <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Integer value) {
            addCriterion("QUESTION_ID <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Integer> values) {
            addCriterion("QUESTION_ID in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Integer> values) {
            addCriterion("QUESTION_ID not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Integer value1, Integer value2) {
            addCriterion("QUESTION_ID between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("QUESTION_ID not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleIsNull() {
            addCriterion("QUESTION_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleIsNotNull() {
            addCriterion("QUESTION_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleEqualTo(String value) {
            addCriterion("QUESTION_TITLE =", value, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleNotEqualTo(String value) {
            addCriterion("QUESTION_TITLE <>", value, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleGreaterThan(String value) {
            addCriterion("QUESTION_TITLE >", value, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTION_TITLE >=", value, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleLessThan(String value) {
            addCriterion("QUESTION_TITLE <", value, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleLessThanOrEqualTo(String value) {
            addCriterion("QUESTION_TITLE <=", value, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleLike(String value) {
            addCriterion("QUESTION_TITLE like", value, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleNotLike(String value) {
            addCriterion("QUESTION_TITLE not like", value, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleIn(List<String> values) {
            addCriterion("QUESTION_TITLE in", values, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleNotIn(List<String> values) {
            addCriterion("QUESTION_TITLE not in", values, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleBetween(String value1, String value2) {
            addCriterion("QUESTION_TITLE between", value1, value2, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionTitleNotBetween(String value1, String value2) {
            addCriterion("QUESTION_TITLE not between", value1, value2, "questionTitle");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceIsNull() {
            addCriterion("QUESTION_SENTENCE is null");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceIsNotNull() {
            addCriterion("QUESTION_SENTENCE is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceEqualTo(String value) {
            addCriterion("QUESTION_SENTENCE =", value, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceNotEqualTo(String value) {
            addCriterion("QUESTION_SENTENCE <>", value, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceGreaterThan(String value) {
            addCriterion("QUESTION_SENTENCE >", value, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTION_SENTENCE >=", value, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceLessThan(String value) {
            addCriterion("QUESTION_SENTENCE <", value, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceLessThanOrEqualTo(String value) {
            addCriterion("QUESTION_SENTENCE <=", value, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceLike(String value) {
            addCriterion("QUESTION_SENTENCE like", value, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceNotLike(String value) {
            addCriterion("QUESTION_SENTENCE not like", value, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceIn(List<String> values) {
            addCriterion("QUESTION_SENTENCE in", values, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceNotIn(List<String> values) {
            addCriterion("QUESTION_SENTENCE not in", values, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceBetween(String value1, String value2) {
            addCriterion("QUESTION_SENTENCE between", value1, value2, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andQuestionSentenceNotBetween(String value1, String value2) {
            addCriterion("QUESTION_SENTENCE not between", value1, value2, "questionSentence");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1IsNull() {
            addCriterion("ANSWER_SENTENCE_1 is null");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1IsNotNull() {
            addCriterion("ANSWER_SENTENCE_1 is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1EqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_1 =", value, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1NotEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_1 <>", value, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1GreaterThan(String value) {
            addCriterion("ANSWER_SENTENCE_1 >", value, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1GreaterThanOrEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_1 >=", value, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1LessThan(String value) {
            addCriterion("ANSWER_SENTENCE_1 <", value, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1LessThanOrEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_1 <=", value, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1Like(String value) {
            addCriterion("ANSWER_SENTENCE_1 like", value, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1NotLike(String value) {
            addCriterion("ANSWER_SENTENCE_1 not like", value, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1In(List<String> values) {
            addCriterion("ANSWER_SENTENCE_1 in", values, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1NotIn(List<String> values) {
            addCriterion("ANSWER_SENTENCE_1 not in", values, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1Between(String value1, String value2) {
            addCriterion("ANSWER_SENTENCE_1 between", value1, value2, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence1NotBetween(String value1, String value2) {
            addCriterion("ANSWER_SENTENCE_1 not between", value1, value2, "answerSentence1");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2IsNull() {
            addCriterion("ANSWER_SENTENCE_2 is null");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2IsNotNull() {
            addCriterion("ANSWER_SENTENCE_2 is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2EqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_2 =", value, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2NotEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_2 <>", value, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2GreaterThan(String value) {
            addCriterion("ANSWER_SENTENCE_2 >", value, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2GreaterThanOrEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_2 >=", value, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2LessThan(String value) {
            addCriterion("ANSWER_SENTENCE_2 <", value, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2LessThanOrEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_2 <=", value, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2Like(String value) {
            addCriterion("ANSWER_SENTENCE_2 like", value, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2NotLike(String value) {
            addCriterion("ANSWER_SENTENCE_2 not like", value, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2In(List<String> values) {
            addCriterion("ANSWER_SENTENCE_2 in", values, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2NotIn(List<String> values) {
            addCriterion("ANSWER_SENTENCE_2 not in", values, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2Between(String value1, String value2) {
            addCriterion("ANSWER_SENTENCE_2 between", value1, value2, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence2NotBetween(String value1, String value2) {
            addCriterion("ANSWER_SENTENCE_2 not between", value1, value2, "answerSentence2");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3IsNull() {
            addCriterion("ANSWER_SENTENCE_3 is null");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3IsNotNull() {
            addCriterion("ANSWER_SENTENCE_3 is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3EqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_3 =", value, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3NotEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_3 <>", value, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3GreaterThan(String value) {
            addCriterion("ANSWER_SENTENCE_3 >", value, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3GreaterThanOrEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_3 >=", value, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3LessThan(String value) {
            addCriterion("ANSWER_SENTENCE_3 <", value, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3LessThanOrEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_3 <=", value, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3Like(String value) {
            addCriterion("ANSWER_SENTENCE_3 like", value, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3NotLike(String value) {
            addCriterion("ANSWER_SENTENCE_3 not like", value, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3In(List<String> values) {
            addCriterion("ANSWER_SENTENCE_3 in", values, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3NotIn(List<String> values) {
            addCriterion("ANSWER_SENTENCE_3 not in", values, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3Between(String value1, String value2) {
            addCriterion("ANSWER_SENTENCE_3 between", value1, value2, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence3NotBetween(String value1, String value2) {
            addCriterion("ANSWER_SENTENCE_3 not between", value1, value2, "answerSentence3");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4IsNull() {
            addCriterion("ANSWER_SENTENCE_4 is null");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4IsNotNull() {
            addCriterion("ANSWER_SENTENCE_4 is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4EqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_4 =", value, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4NotEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_4 <>", value, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4GreaterThan(String value) {
            addCriterion("ANSWER_SENTENCE_4 >", value, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4GreaterThanOrEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_4 >=", value, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4LessThan(String value) {
            addCriterion("ANSWER_SENTENCE_4 <", value, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4LessThanOrEqualTo(String value) {
            addCriterion("ANSWER_SENTENCE_4 <=", value, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4Like(String value) {
            addCriterion("ANSWER_SENTENCE_4 like", value, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4NotLike(String value) {
            addCriterion("ANSWER_SENTENCE_4 not like", value, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4In(List<String> values) {
            addCriterion("ANSWER_SENTENCE_4 in", values, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4NotIn(List<String> values) {
            addCriterion("ANSWER_SENTENCE_4 not in", values, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4Between(String value1, String value2) {
            addCriterion("ANSWER_SENTENCE_4 between", value1, value2, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andAnswerSentence4NotBetween(String value1, String value2) {
            addCriterion("ANSWER_SENTENCE_4 not between", value1, value2, "answerSentence4");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberIsNull() {
            addCriterion("CORRECT_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberIsNotNull() {
            addCriterion("CORRECT_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberEqualTo(Integer value) {
            addCriterion("CORRECT_NUMBER =", value, "correctNumber");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberNotEqualTo(Integer value) {
            addCriterion("CORRECT_NUMBER <>", value, "correctNumber");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberGreaterThan(Integer value) {
            addCriterion("CORRECT_NUMBER >", value, "correctNumber");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("CORRECT_NUMBER >=", value, "correctNumber");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberLessThan(Integer value) {
            addCriterion("CORRECT_NUMBER <", value, "correctNumber");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberLessThanOrEqualTo(Integer value) {
            addCriterion("CORRECT_NUMBER <=", value, "correctNumber");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberIn(List<Integer> values) {
            addCriterion("CORRECT_NUMBER in", values, "correctNumber");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberNotIn(List<Integer> values) {
            addCriterion("CORRECT_NUMBER not in", values, "correctNumber");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberBetween(Integer value1, Integer value2) {
            addCriterion("CORRECT_NUMBER between", value1, value2, "correctNumber");
            return (Criteria) this;
        }

        public Criteria andCorrectNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("CORRECT_NUMBER not between", value1, value2, "correctNumber");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("COMMENT is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("COMMENT is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("COMMENT =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("COMMENT <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("COMMENT >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENT >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("COMMENT <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("COMMENT <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("COMMENT like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("COMMENT not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("COMMENT in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("COMMENT not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("COMMENT between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("COMMENT not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNull() {
            addCriterion("REGISTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNotNull() {
            addCriterion("REGISTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdEqualTo(String value) {
            addCriterion("REGISTER_ID =", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotEqualTo(String value) {
            addCriterion("REGISTER_ID <>", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThan(String value) {
            addCriterion("REGISTER_ID >", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID >=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThan(String value) {
            addCriterion("REGISTER_ID <", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID <=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLike(String value) {
            addCriterion("REGISTER_ID like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotLike(String value) {
            addCriterion("REGISTER_ID not like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIn(List<String> values) {
            addCriterion("REGISTER_ID in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotIn(List<String> values) {
            addCriterion("REGISTER_ID not in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdBetween(String value1, String value2) {
            addCriterion("REGISTER_ID between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotBetween(String value1, String value2) {
            addCriterion("REGISTER_ID not between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNull() {
            addCriterion("REGISTER_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNotNull() {
            addCriterion("REGISTER_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeEqualTo(Date value) {
            addCriterion("REGISTER_DATIME =", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <>", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThan(Date value) {
            addCriterion("REGISTER_DATIME >", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME >=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThan(Date value) {
            addCriterion("REGISTER_DATIME <", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIn(List<Date> values) {
            addCriterion("REGISTER_DATIME in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotIn(List<Date> values) {
            addCriterion("REGISTER_DATIME not in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME not between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("UPDATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("UPDATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(String value) {
            addCriterion("UPDATE_ID =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(String value) {
            addCriterion("UPDATE_ID <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(String value) {
            addCriterion("UPDATE_ID >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(String value) {
            addCriterion("UPDATE_ID <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLike(String value) {
            addCriterion("UPDATE_ID like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotLike(String value) {
            addCriterion("UPDATE_ID not like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<String> values) {
            addCriterion("UPDATE_ID in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<String> values) {
            addCriterion("UPDATE_ID not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(String value1, String value2) {
            addCriterion("UPDATE_ID between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_ID not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNull() {
            addCriterion("UPDATE_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNotNull() {
            addCriterion("UPDATE_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeEqualTo(Date value) {
            addCriterion("UPDATE_DATIME =", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <>", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThan(Date value) {
            addCriterion("UPDATE_DATIME >", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME >=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThan(Date value) {
            addCriterion("UPDATE_DATIME <", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIn(List<Date> values) {
            addCriterion("UPDATE_DATIME in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotIn(List<Date> values) {
            addCriterion("UPDATE_DATIME not in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME between", value1, value2, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME not between", value1, value2, "updateDatime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_question
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 20 23:57:36 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_question
     *
     * @mbg.generated Tue Mar 20 23:57:36 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}