package jp.co.pds.PJ0001.dao.dto;

public class MsQuestionGroupQuestionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_question_group_question.QUESTION_GROUP_ID
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    private Integer questionGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_question_group_question.QUESTION_ID
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    private Integer questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_question_group_question.QUESTION_GROUP_ID
     *
     * @return the value of ms_question_group_question.QUESTION_GROUP_ID
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    public Integer getQuestionGroupId() {
        return questionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_question_group_question.QUESTION_GROUP_ID
     *
     * @param questionGroupId the value for ms_question_group_question.QUESTION_GROUP_ID
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    public void setQuestionGroupId(Integer questionGroupId) {
        this.questionGroupId = questionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_question_group_question.QUESTION_ID
     *
     * @return the value of ms_question_group_question.QUESTION_ID
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_question_group_question.QUESTION_ID
     *
     * @param questionId the value for ms_question_group_question.QUESTION_ID
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
}