package jp.co.pds.PJ0001.dao.mapper;

import java.util.List;
import jp.co.pds.PJ0001.dao.dto.DtAnswerDetail;
import jp.co.pds.PJ0001.dao.dto.DtAnswerDetailExample;
import jp.co.pds.PJ0001.dao.dto.DtAnswerDetailKey;
import org.apache.ibatis.annotations.Param;

public interface DtAnswerDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    long countByExample(DtAnswerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int deleteByExample(DtAnswerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int deleteByPrimaryKey(DtAnswerDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int insert(DtAnswerDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int insertSelective(DtAnswerDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    List<DtAnswerDetail> selectByExample(DtAnswerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    DtAnswerDetail selectByPrimaryKey(DtAnswerDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int updateByExampleSelective(@Param("record") DtAnswerDetail record, @Param("example") DtAnswerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int updateByExample(@Param("record") DtAnswerDetail record, @Param("example") DtAnswerDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int updateByPrimaryKeySelective(DtAnswerDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer_detail
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int updateByPrimaryKey(DtAnswerDetail record);
}