package jp.co.pds.PJ0001.dao.mapper;

import java.util.List;
import jp.co.pds.PJ0001.dao.dto.DtAnswer;
import jp.co.pds.PJ0001.dao.dto.DtAnswerExample;
import org.apache.ibatis.annotations.Param;

public interface DtAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    long countByExample(DtAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int deleteByExample(DtAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int deleteByPrimaryKey(Integer answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int insert(DtAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int insertSelective(DtAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    List<DtAnswer> selectByExample(DtAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    DtAnswer selectByPrimaryKey(Integer answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int updateByExampleSelective(@Param("record") DtAnswer record, @Param("example") DtAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int updateByExample(@Param("record") DtAnswer record, @Param("example") DtAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int updateByPrimaryKeySelective(DtAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_answer
     *
     * @mbg.generated Sat Mar 24 16:57:26 JST 2018
     */
    int updateByPrimaryKey(DtAnswer record);
}