package jp.co.pds.PJ0001.dao.mapper;

import java.util.List;
import jp.co.pds.PJ0001.dao.dto.MsQuestionGroupQuestion;
import jp.co.pds.PJ0001.dao.dto.MsQuestionGroupQuestionExample;
import jp.co.pds.PJ0001.dao.dto.MsQuestionGroupQuestionKey;
import org.apache.ibatis.annotations.Param;

public interface MsQuestionGroupQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    long countByExample(MsQuestionGroupQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    int deleteByExample(MsQuestionGroupQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    int deleteByPrimaryKey(MsQuestionGroupQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    int insert(MsQuestionGroupQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    int insertSelective(MsQuestionGroupQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    List<MsQuestionGroupQuestion> selectByExample(MsQuestionGroupQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    MsQuestionGroupQuestion selectByPrimaryKey(MsQuestionGroupQuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    int updateByExampleSelective(@Param("record") MsQuestionGroupQuestion record, @Param("example") MsQuestionGroupQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    int updateByExample(@Param("record") MsQuestionGroupQuestion record, @Param("example") MsQuestionGroupQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    int updateByPrimaryKeySelective(MsQuestionGroupQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_question_group_question
     *
     * @mbg.generated Mon Mar 19 15:57:02 JST 2018
     */
    int updateByPrimaryKey(MsQuestionGroupQuestion record);
}