package jp.co.pds.common.dao.dto;

import java.util.Date;

public class DtLoginHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_login_history.LOGIN_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    private Integer loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_login_history.USER_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_login_history.CLIENT_INFO
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    private String clientInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_login_history.REGISTER_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    private String registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_login_history.REGISTER_DATIME
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    private Date registerDatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_login_history.UPDATE_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_login_history.UPDATE_DATIME
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    private Date updateDatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_login_history.LOGIN_ID
     *
     * @return the value of dt_login_history.LOGIN_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_login_history.LOGIN_ID
     *
     * @param loginId the value for dt_login_history.LOGIN_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_login_history.USER_ID
     *
     * @return the value of dt_login_history.USER_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_login_history.USER_ID
     *
     * @param userId the value for dt_login_history.USER_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_login_history.CLIENT_INFO
     *
     * @return the value of dt_login_history.CLIENT_INFO
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public String getClientInfo() {
        return clientInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_login_history.CLIENT_INFO
     *
     * @param clientInfo the value for dt_login_history.CLIENT_INFO
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public void setClientInfo(String clientInfo) {
        this.clientInfo = clientInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_login_history.REGISTER_ID
     *
     * @return the value of dt_login_history.REGISTER_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public String getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_login_history.REGISTER_ID
     *
     * @param registerId the value for dt_login_history.REGISTER_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public void setRegisterId(String registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_login_history.REGISTER_DATIME
     *
     * @return the value of dt_login_history.REGISTER_DATIME
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public Date getRegisterDatime() {
        return registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_login_history.REGISTER_DATIME
     *
     * @param registerDatime the value for dt_login_history.REGISTER_DATIME
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public void setRegisterDatime(Date registerDatime) {
        this.registerDatime = registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_login_history.UPDATE_ID
     *
     * @return the value of dt_login_history.UPDATE_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_login_history.UPDATE_ID
     *
     * @param updateId the value for dt_login_history.UPDATE_ID
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_login_history.UPDATE_DATIME
     *
     * @return the value of dt_login_history.UPDATE_DATIME
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public Date getUpdateDatime() {
        return updateDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_login_history.UPDATE_DATIME
     *
     * @param updateDatime the value for dt_login_history.UPDATE_DATIME
     *
     * @mbg.generated Sat Apr 07 01:57:40 JST 2018
     */
    public void setUpdateDatime(Date updateDatime) {
        this.updateDatime = updateDatime;
    }
}