package jp.co.pds.common.dao.dto;

public class MsCompanyGroupKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_company_group.COMPANY_CD
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    private String companyCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_company_group.GROUP_ID
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_company_group.COMPANY_CD
     *
     * @return the value of ms_company_group.COMPANY_CD
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    public String getCompanyCd() {
        return companyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_company_group.COMPANY_CD
     *
     * @param companyCd the value for ms_company_group.COMPANY_CD
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    public void setCompanyCd(String companyCd) {
        this.companyCd = companyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_company_group.GROUP_ID
     *
     * @return the value of ms_company_group.GROUP_ID
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_company_group.GROUP_ID
     *
     * @param groupId the value for ms_company_group.GROUP_ID
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}