package jp.co.pds.common.dao.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MsCompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public MsCompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompanyCdIsNull() {
            addCriterion("COMPANY_CD is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCdIsNotNull() {
            addCriterion("COMPANY_CD is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCdEqualTo(String value) {
            addCriterion("COMPANY_CD =", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdNotEqualTo(String value) {
            addCriterion("COMPANY_CD <>", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdGreaterThan(String value) {
            addCriterion("COMPANY_CD >", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_CD >=", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdLessThan(String value) {
            addCriterion("COMPANY_CD <", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_CD <=", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdLike(String value) {
            addCriterion("COMPANY_CD like", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdNotLike(String value) {
            addCriterion("COMPANY_CD not like", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdIn(List<String> values) {
            addCriterion("COMPANY_CD in", values, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdNotIn(List<String> values) {
            addCriterion("COMPANY_CD not in", values, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdBetween(String value1, String value2) {
            addCriterion("COMPANY_CD between", value1, value2, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdNotBetween(String value1, String value2) {
            addCriterion("COMPANY_CD not between", value1, value2, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("COMPANY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("COMPANY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("COMPANY_NAME =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("COMPANY_NAME <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("COMPANY_NAME >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("COMPANY_NAME <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("COMPANY_NAME like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("COMPANY_NAME not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("COMPANY_NAME in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("COMPANY_NAME not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andPostalCdIsNull() {
            addCriterion("POSTAL_CD is null");
            return (Criteria) this;
        }

        public Criteria andPostalCdIsNotNull() {
            addCriterion("POSTAL_CD is not null");
            return (Criteria) this;
        }

        public Criteria andPostalCdEqualTo(String value) {
            addCriterion("POSTAL_CD =", value, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdNotEqualTo(String value) {
            addCriterion("POSTAL_CD <>", value, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdGreaterThan(String value) {
            addCriterion("POSTAL_CD >", value, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdGreaterThanOrEqualTo(String value) {
            addCriterion("POSTAL_CD >=", value, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdLessThan(String value) {
            addCriterion("POSTAL_CD <", value, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdLessThanOrEqualTo(String value) {
            addCriterion("POSTAL_CD <=", value, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdLike(String value) {
            addCriterion("POSTAL_CD like", value, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdNotLike(String value) {
            addCriterion("POSTAL_CD not like", value, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdIn(List<String> values) {
            addCriterion("POSTAL_CD in", values, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdNotIn(List<String> values) {
            addCriterion("POSTAL_CD not in", values, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdBetween(String value1, String value2) {
            addCriterion("POSTAL_CD between", value1, value2, "postalCd");
            return (Criteria) this;
        }

        public Criteria andPostalCdNotBetween(String value1, String value2) {
            addCriterion("POSTAL_CD not between", value1, value2, "postalCd");
            return (Criteria) this;
        }

        public Criteria andAddr1IsNull() {
            addCriterion("ADDR_1 is null");
            return (Criteria) this;
        }

        public Criteria andAddr1IsNotNull() {
            addCriterion("ADDR_1 is not null");
            return (Criteria) this;
        }

        public Criteria andAddr1EqualTo(String value) {
            addCriterion("ADDR_1 =", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1NotEqualTo(String value) {
            addCriterion("ADDR_1 <>", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1GreaterThan(String value) {
            addCriterion("ADDR_1 >", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1GreaterThanOrEqualTo(String value) {
            addCriterion("ADDR_1 >=", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1LessThan(String value) {
            addCriterion("ADDR_1 <", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1LessThanOrEqualTo(String value) {
            addCriterion("ADDR_1 <=", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1Like(String value) {
            addCriterion("ADDR_1 like", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1NotLike(String value) {
            addCriterion("ADDR_1 not like", value, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1In(List<String> values) {
            addCriterion("ADDR_1 in", values, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1NotIn(List<String> values) {
            addCriterion("ADDR_1 not in", values, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1Between(String value1, String value2) {
            addCriterion("ADDR_1 between", value1, value2, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr1NotBetween(String value1, String value2) {
            addCriterion("ADDR_1 not between", value1, value2, "addr1");
            return (Criteria) this;
        }

        public Criteria andAddr2IsNull() {
            addCriterion("ADDR_2 is null");
            return (Criteria) this;
        }

        public Criteria andAddr2IsNotNull() {
            addCriterion("ADDR_2 is not null");
            return (Criteria) this;
        }

        public Criteria andAddr2EqualTo(String value) {
            addCriterion("ADDR_2 =", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2NotEqualTo(String value) {
            addCriterion("ADDR_2 <>", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2GreaterThan(String value) {
            addCriterion("ADDR_2 >", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2GreaterThanOrEqualTo(String value) {
            addCriterion("ADDR_2 >=", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2LessThan(String value) {
            addCriterion("ADDR_2 <", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2LessThanOrEqualTo(String value) {
            addCriterion("ADDR_2 <=", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2Like(String value) {
            addCriterion("ADDR_2 like", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2NotLike(String value) {
            addCriterion("ADDR_2 not like", value, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2In(List<String> values) {
            addCriterion("ADDR_2 in", values, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2NotIn(List<String> values) {
            addCriterion("ADDR_2 not in", values, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2Between(String value1, String value2) {
            addCriterion("ADDR_2 between", value1, value2, "addr2");
            return (Criteria) this;
        }

        public Criteria andAddr2NotBetween(String value1, String value2) {
            addCriterion("ADDR_2 not between", value1, value2, "addr2");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdIsNull() {
            addCriterion("RPRSTTV_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdIsNotNull() {
            addCriterion("RPRSTTV_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdEqualTo(String value) {
            addCriterion("RPRSTTV_USER_ID =", value, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdNotEqualTo(String value) {
            addCriterion("RPRSTTV_USER_ID <>", value, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdGreaterThan(String value) {
            addCriterion("RPRSTTV_USER_ID >", value, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("RPRSTTV_USER_ID >=", value, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdLessThan(String value) {
            addCriterion("RPRSTTV_USER_ID <", value, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdLessThanOrEqualTo(String value) {
            addCriterion("RPRSTTV_USER_ID <=", value, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdLike(String value) {
            addCriterion("RPRSTTV_USER_ID like", value, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdNotLike(String value) {
            addCriterion("RPRSTTV_USER_ID not like", value, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdIn(List<String> values) {
            addCriterion("RPRSTTV_USER_ID in", values, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdNotIn(List<String> values) {
            addCriterion("RPRSTTV_USER_ID not in", values, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdBetween(String value1, String value2) {
            addCriterion("RPRSTTV_USER_ID between", value1, value2, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andRprsttvUserIdNotBetween(String value1, String value2) {
            addCriterion("RPRSTTV_USER_ID not between", value1, value2, "rprsttvUserId");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntIsNull() {
            addCriterion("MAX_LOGIN_TRIAL_CNT is null");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntIsNotNull() {
            addCriterion("MAX_LOGIN_TRIAL_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntEqualTo(Integer value) {
            addCriterion("MAX_LOGIN_TRIAL_CNT =", value, "maxLoginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntNotEqualTo(Integer value) {
            addCriterion("MAX_LOGIN_TRIAL_CNT <>", value, "maxLoginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntGreaterThan(Integer value) {
            addCriterion("MAX_LOGIN_TRIAL_CNT >", value, "maxLoginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("MAX_LOGIN_TRIAL_CNT >=", value, "maxLoginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntLessThan(Integer value) {
            addCriterion("MAX_LOGIN_TRIAL_CNT <", value, "maxLoginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntLessThanOrEqualTo(Integer value) {
            addCriterion("MAX_LOGIN_TRIAL_CNT <=", value, "maxLoginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntIn(List<Integer> values) {
            addCriterion("MAX_LOGIN_TRIAL_CNT in", values, "maxLoginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntNotIn(List<Integer> values) {
            addCriterion("MAX_LOGIN_TRIAL_CNT not in", values, "maxLoginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntBetween(Integer value1, Integer value2) {
            addCriterion("MAX_LOGIN_TRIAL_CNT between", value1, value2, "maxLoginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andMaxLoginTrialCntNotBetween(Integer value1, Integer value2) {
            addCriterion("MAX_LOGIN_TRIAL_CNT not between", value1, value2, "maxLoginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntIsNull() {
            addCriterion("PSWD_HISTORY_CNT is null");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntIsNotNull() {
            addCriterion("PSWD_HISTORY_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntEqualTo(Integer value) {
            addCriterion("PSWD_HISTORY_CNT =", value, "pswdHistoryCnt");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntNotEqualTo(Integer value) {
            addCriterion("PSWD_HISTORY_CNT <>", value, "pswdHistoryCnt");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntGreaterThan(Integer value) {
            addCriterion("PSWD_HISTORY_CNT >", value, "pswdHistoryCnt");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("PSWD_HISTORY_CNT >=", value, "pswdHistoryCnt");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntLessThan(Integer value) {
            addCriterion("PSWD_HISTORY_CNT <", value, "pswdHistoryCnt");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntLessThanOrEqualTo(Integer value) {
            addCriterion("PSWD_HISTORY_CNT <=", value, "pswdHistoryCnt");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntIn(List<Integer> values) {
            addCriterion("PSWD_HISTORY_CNT in", values, "pswdHistoryCnt");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntNotIn(List<Integer> values) {
            addCriterion("PSWD_HISTORY_CNT not in", values, "pswdHistoryCnt");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntBetween(Integer value1, Integer value2) {
            addCriterion("PSWD_HISTORY_CNT between", value1, value2, "pswdHistoryCnt");
            return (Criteria) this;
        }

        public Criteria andPswdHistoryCntNotBetween(Integer value1, Integer value2) {
            addCriterion("PSWD_HISTORY_CNT not between", value1, value2, "pswdHistoryCnt");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermIsNull() {
            addCriterion("PSWD_VALID_TERM is null");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermIsNotNull() {
            addCriterion("PSWD_VALID_TERM is not null");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermEqualTo(Integer value) {
            addCriterion("PSWD_VALID_TERM =", value, "pswdValidTerm");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermNotEqualTo(Integer value) {
            addCriterion("PSWD_VALID_TERM <>", value, "pswdValidTerm");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermGreaterThan(Integer value) {
            addCriterion("PSWD_VALID_TERM >", value, "pswdValidTerm");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermGreaterThanOrEqualTo(Integer value) {
            addCriterion("PSWD_VALID_TERM >=", value, "pswdValidTerm");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermLessThan(Integer value) {
            addCriterion("PSWD_VALID_TERM <", value, "pswdValidTerm");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermLessThanOrEqualTo(Integer value) {
            addCriterion("PSWD_VALID_TERM <=", value, "pswdValidTerm");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermIn(List<Integer> values) {
            addCriterion("PSWD_VALID_TERM in", values, "pswdValidTerm");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermNotIn(List<Integer> values) {
            addCriterion("PSWD_VALID_TERM not in", values, "pswdValidTerm");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermBetween(Integer value1, Integer value2) {
            addCriterion("PSWD_VALID_TERM between", value1, value2, "pswdValidTerm");
            return (Criteria) this;
        }

        public Criteria andPswdValidTermNotBetween(Integer value1, Integer value2) {
            addCriterion("PSWD_VALID_TERM not between", value1, value2, "pswdValidTerm");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNull() {
            addCriterion("REGISTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNotNull() {
            addCriterion("REGISTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdEqualTo(String value) {
            addCriterion("REGISTER_ID =", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotEqualTo(String value) {
            addCriterion("REGISTER_ID <>", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThan(String value) {
            addCriterion("REGISTER_ID >", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID >=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThan(String value) {
            addCriterion("REGISTER_ID <", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID <=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLike(String value) {
            addCriterion("REGISTER_ID like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotLike(String value) {
            addCriterion("REGISTER_ID not like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIn(List<String> values) {
            addCriterion("REGISTER_ID in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotIn(List<String> values) {
            addCriterion("REGISTER_ID not in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdBetween(String value1, String value2) {
            addCriterion("REGISTER_ID between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotBetween(String value1, String value2) {
            addCriterion("REGISTER_ID not between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNull() {
            addCriterion("REGISTER_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNotNull() {
            addCriterion("REGISTER_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeEqualTo(Date value) {
            addCriterion("REGISTER_DATIME =", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <>", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThan(Date value) {
            addCriterion("REGISTER_DATIME >", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME >=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThan(Date value) {
            addCriterion("REGISTER_DATIME <", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIn(List<Date> values) {
            addCriterion("REGISTER_DATIME in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotIn(List<Date> values) {
            addCriterion("REGISTER_DATIME not in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME not between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("UPDATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("UPDATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(String value) {
            addCriterion("UPDATE_ID =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(String value) {
            addCriterion("UPDATE_ID <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(String value) {
            addCriterion("UPDATE_ID >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(String value) {
            addCriterion("UPDATE_ID <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLike(String value) {
            addCriterion("UPDATE_ID like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotLike(String value) {
            addCriterion("UPDATE_ID not like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<String> values) {
            addCriterion("UPDATE_ID in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<String> values) {
            addCriterion("UPDATE_ID not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(String value1, String value2) {
            addCriterion("UPDATE_ID between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_ID not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNull() {
            addCriterion("UPDATE_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNotNull() {
            addCriterion("UPDATE_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeEqualTo(Date value) {
            addCriterion("UPDATE_DATIME =", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <>", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThan(Date value) {
            addCriterion("UPDATE_DATIME >", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME >=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThan(Date value) {
            addCriterion("UPDATE_DATIME <", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIn(List<Date> values) {
            addCriterion("UPDATE_DATIME in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotIn(List<Date> values) {
            addCriterion("UPDATE_DATIME not in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME between", value1, value2, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME not between", value1, value2, "updateDatime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_company
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 20 22:32:41 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_company
     *
     * @mbg.generated Fri Apr 20 22:32:41 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}