package jp.co.pds.common.dao.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MsDateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public MsDateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCalendarYyIsNull() {
            addCriterion("CALENDAR_YY is null");
            return (Criteria) this;
        }

        public Criteria andCalendarYyIsNotNull() {
            addCriterion("CALENDAR_YY is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarYyEqualTo(Integer value) {
            addCriterion("CALENDAR_YY =", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyNotEqualTo(Integer value) {
            addCriterion("CALENDAR_YY <>", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyGreaterThan(Integer value) {
            addCriterion("CALENDAR_YY >", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyGreaterThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_YY >=", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyLessThan(Integer value) {
            addCriterion("CALENDAR_YY <", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyLessThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_YY <=", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyIn(List<Integer> values) {
            addCriterion("CALENDAR_YY in", values, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyNotIn(List<Integer> values) {
            addCriterion("CALENDAR_YY not in", values, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_YY between", value1, value2, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyNotBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_YY not between", value1, value2, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarMmIsNull() {
            addCriterion("CALENDAR_MM is null");
            return (Criteria) this;
        }

        public Criteria andCalendarMmIsNotNull() {
            addCriterion("CALENDAR_MM is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarMmEqualTo(Integer value) {
            addCriterion("CALENDAR_MM =", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmNotEqualTo(Integer value) {
            addCriterion("CALENDAR_MM <>", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmGreaterThan(Integer value) {
            addCriterion("CALENDAR_MM >", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmGreaterThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_MM >=", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmLessThan(Integer value) {
            addCriterion("CALENDAR_MM <", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmLessThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_MM <=", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmIn(List<Integer> values) {
            addCriterion("CALENDAR_MM in", values, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmNotIn(List<Integer> values) {
            addCriterion("CALENDAR_MM not in", values, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_MM between", value1, value2, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmNotBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_MM not between", value1, value2, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarDdIsNull() {
            addCriterion("CALENDAR_DD is null");
            return (Criteria) this;
        }

        public Criteria andCalendarDdIsNotNull() {
            addCriterion("CALENDAR_DD is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarDdEqualTo(Integer value) {
            addCriterion("CALENDAR_DD =", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdNotEqualTo(Integer value) {
            addCriterion("CALENDAR_DD <>", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdGreaterThan(Integer value) {
            addCriterion("CALENDAR_DD >", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_DD >=", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdLessThan(Integer value) {
            addCriterion("CALENDAR_DD <", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdLessThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_DD <=", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdIn(List<Integer> values) {
            addCriterion("CALENDAR_DD in", values, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdNotIn(List<Integer> values) {
            addCriterion("CALENDAR_DD not in", values, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_DD between", value1, value2, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdNotBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_DD not between", value1, value2, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdIsNull() {
            addCriterion("WEEKDAY_CD is null");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdIsNotNull() {
            addCriterion("WEEKDAY_CD is not null");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdEqualTo(String value) {
            addCriterion("WEEKDAY_CD =", value, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdNotEqualTo(String value) {
            addCriterion("WEEKDAY_CD <>", value, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdGreaterThan(String value) {
            addCriterion("WEEKDAY_CD >", value, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdGreaterThanOrEqualTo(String value) {
            addCriterion("WEEKDAY_CD >=", value, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdLessThan(String value) {
            addCriterion("WEEKDAY_CD <", value, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdLessThanOrEqualTo(String value) {
            addCriterion("WEEKDAY_CD <=", value, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdLike(String value) {
            addCriterion("WEEKDAY_CD like", value, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdNotLike(String value) {
            addCriterion("WEEKDAY_CD not like", value, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdIn(List<String> values) {
            addCriterion("WEEKDAY_CD in", values, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdNotIn(List<String> values) {
            addCriterion("WEEKDAY_CD not in", values, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdBetween(String value1, String value2) {
            addCriterion("WEEKDAY_CD between", value1, value2, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andWeekdayCdNotBetween(String value1, String value2) {
            addCriterion("WEEKDAY_CD not between", value1, value2, "weekdayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdIsNull() {
            addCriterion("HOLIDAY_CD is null");
            return (Criteria) this;
        }

        public Criteria andHolidayCdIsNotNull() {
            addCriterion("HOLIDAY_CD is not null");
            return (Criteria) this;
        }

        public Criteria andHolidayCdEqualTo(String value) {
            addCriterion("HOLIDAY_CD =", value, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdNotEqualTo(String value) {
            addCriterion("HOLIDAY_CD <>", value, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdGreaterThan(String value) {
            addCriterion("HOLIDAY_CD >", value, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdGreaterThanOrEqualTo(String value) {
            addCriterion("HOLIDAY_CD >=", value, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdLessThan(String value) {
            addCriterion("HOLIDAY_CD <", value, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdLessThanOrEqualTo(String value) {
            addCriterion("HOLIDAY_CD <=", value, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdLike(String value) {
            addCriterion("HOLIDAY_CD like", value, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdNotLike(String value) {
            addCriterion("HOLIDAY_CD not like", value, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdIn(List<String> values) {
            addCriterion("HOLIDAY_CD in", values, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdNotIn(List<String> values) {
            addCriterion("HOLIDAY_CD not in", values, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdBetween(String value1, String value2) {
            addCriterion("HOLIDAY_CD between", value1, value2, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andHolidayCdNotBetween(String value1, String value2) {
            addCriterion("HOLIDAY_CD not between", value1, value2, "holidayCd");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNull() {
            addCriterion("REGISTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNotNull() {
            addCriterion("REGISTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdEqualTo(String value) {
            addCriterion("REGISTER_ID =", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotEqualTo(String value) {
            addCriterion("REGISTER_ID <>", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThan(String value) {
            addCriterion("REGISTER_ID >", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID >=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThan(String value) {
            addCriterion("REGISTER_ID <", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID <=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLike(String value) {
            addCriterion("REGISTER_ID like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotLike(String value) {
            addCriterion("REGISTER_ID not like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIn(List<String> values) {
            addCriterion("REGISTER_ID in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotIn(List<String> values) {
            addCriterion("REGISTER_ID not in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdBetween(String value1, String value2) {
            addCriterion("REGISTER_ID between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotBetween(String value1, String value2) {
            addCriterion("REGISTER_ID not between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNull() {
            addCriterion("REGISTER_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNotNull() {
            addCriterion("REGISTER_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeEqualTo(Date value) {
            addCriterion("REGISTER_DATIME =", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <>", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThan(Date value) {
            addCriterion("REGISTER_DATIME >", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME >=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThan(Date value) {
            addCriterion("REGISTER_DATIME <", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIn(List<Date> values) {
            addCriterion("REGISTER_DATIME in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotIn(List<Date> values) {
            addCriterion("REGISTER_DATIME not in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME not between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("UPDATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("UPDATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(String value) {
            addCriterion("UPDATE_ID =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(String value) {
            addCriterion("UPDATE_ID <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(String value) {
            addCriterion("UPDATE_ID >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(String value) {
            addCriterion("UPDATE_ID <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLike(String value) {
            addCriterion("UPDATE_ID like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotLike(String value) {
            addCriterion("UPDATE_ID not like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<String> values) {
            addCriterion("UPDATE_ID in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<String> values) {
            addCriterion("UPDATE_ID not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(String value1, String value2) {
            addCriterion("UPDATE_ID between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_ID not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNull() {
            addCriterion("UPDATE_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNotNull() {
            addCriterion("UPDATE_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeEqualTo(Date value) {
            addCriterion("UPDATE_DATIME =", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <>", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThan(Date value) {
            addCriterion("UPDATE_DATIME >", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME >=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThan(Date value) {
            addCriterion("UPDATE_DATIME <", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIn(List<Date> values) {
            addCriterion("UPDATE_DATIME in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotIn(List<Date> values) {
            addCriterion("UPDATE_DATIME not in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME between", value1, value2, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME not between", value1, value2, "updateDatime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_date
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 08 08:38:07 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}