package jp.co.pds.common.dao.dto;

import java.util.Date;

public class MsGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group.GROUP_ID
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group.GROUP_NAME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group.WORK_START_TIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    private String workStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group.WORK_END_TIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    private String workEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group.WORK_TIME_TRUNC_UNIT
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    private Integer workTimeTruncUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group.REGISTER_ID
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    private String registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group.REGISTER_DATIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    private Date registerDatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group.UPDATE_ID
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group.UPDATE_DATIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    private Date updateDatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group.GROUP_ID
     *
     * @return the value of ms_group.GROUP_ID
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group.GROUP_ID
     *
     * @param groupId the value for ms_group.GROUP_ID
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group.GROUP_NAME
     *
     * @return the value of ms_group.GROUP_NAME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group.GROUP_NAME
     *
     * @param groupName the value for ms_group.GROUP_NAME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group.WORK_START_TIME
     *
     * @return the value of ms_group.WORK_START_TIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public String getWorkStartTime() {
        return workStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group.WORK_START_TIME
     *
     * @param workStartTime the value for ms_group.WORK_START_TIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public void setWorkStartTime(String workStartTime) {
        this.workStartTime = workStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group.WORK_END_TIME
     *
     * @return the value of ms_group.WORK_END_TIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public String getWorkEndTime() {
        return workEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group.WORK_END_TIME
     *
     * @param workEndTime the value for ms_group.WORK_END_TIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public void setWorkEndTime(String workEndTime) {
        this.workEndTime = workEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group.WORK_TIME_TRUNC_UNIT
     *
     * @return the value of ms_group.WORK_TIME_TRUNC_UNIT
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public Integer getWorkTimeTruncUnit() {
        return workTimeTruncUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group.WORK_TIME_TRUNC_UNIT
     *
     * @param workTimeTruncUnit the value for ms_group.WORK_TIME_TRUNC_UNIT
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public void setWorkTimeTruncUnit(Integer workTimeTruncUnit) {
        this.workTimeTruncUnit = workTimeTruncUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group.REGISTER_ID
     *
     * @return the value of ms_group.REGISTER_ID
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public String getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group.REGISTER_ID
     *
     * @param registerId the value for ms_group.REGISTER_ID
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public void setRegisterId(String registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group.REGISTER_DATIME
     *
     * @return the value of ms_group.REGISTER_DATIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public Date getRegisterDatime() {
        return registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group.REGISTER_DATIME
     *
     * @param registerDatime the value for ms_group.REGISTER_DATIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public void setRegisterDatime(Date registerDatime) {
        this.registerDatime = registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group.UPDATE_ID
     *
     * @return the value of ms_group.UPDATE_ID
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group.UPDATE_ID
     *
     * @param updateId the value for ms_group.UPDATE_ID
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group.UPDATE_DATIME
     *
     * @return the value of ms_group.UPDATE_DATIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public Date getUpdateDatime() {
        return updateDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group.UPDATE_DATIME
     *
     * @param updateDatime the value for ms_group.UPDATE_DATIME
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    public void setUpdateDatime(Date updateDatime) {
        this.updateDatime = updateDatime;
    }
}