package jp.co.pds.common.dao.dto;

public class MsGroupUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group_user.GROUP_ID
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group_user.USER_ID
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group_user.GROUP_ID
     *
     * @return the value of ms_group_user.GROUP_ID
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group_user.GROUP_ID
     *
     * @param groupId the value for ms_group_user.GROUP_ID
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group_user.USER_ID
     *
     * @return the value of ms_group_user.USER_ID
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group_user.USER_ID
     *
     * @param userId the value for ms_group_user.USER_ID
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}