package jp.co.pds.common.dao.dto;

public class MsGroupRestTimeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group_rest_time.GROUP_ID
     *
     * @mbg.generated Thu Apr 12 22:44:26 JST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_group_rest_time.REST_TIME_ID
     *
     * @mbg.generated Thu Apr 12 22:44:26 JST 2018
     */
    private Integer restTimeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group_rest_time.GROUP_ID
     *
     * @return the value of ms_group_rest_time.GROUP_ID
     *
     * @mbg.generated Thu Apr 12 22:44:26 JST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group_rest_time.GROUP_ID
     *
     * @param groupId the value for ms_group_rest_time.GROUP_ID
     *
     * @mbg.generated Thu Apr 12 22:44:26 JST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_group_rest_time.REST_TIME_ID
     *
     * @return the value of ms_group_rest_time.REST_TIME_ID
     *
     * @mbg.generated Thu Apr 12 22:44:26 JST 2018
     */
    public Integer getRestTimeId() {
        return restTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_group_rest_time.REST_TIME_ID
     *
     * @param restTimeId the value for ms_group_rest_time.REST_TIME_ID
     *
     * @mbg.generated Thu Apr 12 22:44:26 JST 2018
     */
    public void setRestTimeId(Integer restTimeId) {
        this.restTimeId = restTimeId;
    }
}