package jp.co.pds.common.dao.dto;

import java.util.Date;

public class MsSeq {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_seq.SEQ_NAME
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    private String seqName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_seq.SEQ_VALUE
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    private Integer seqValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_seq.REGISTER_ID
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    private String registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_seq.REGISTER_DATIME
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    private Date registerDatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_seq.UPDATE_ID
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_seq.UPDATE_DATIME
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    private Date updateDatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_seq.SEQ_NAME
     *
     * @return the value of ms_seq.SEQ_NAME
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public String getSeqName() {
        return seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_seq.SEQ_NAME
     *
     * @param seqName the value for ms_seq.SEQ_NAME
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public void setSeqName(String seqName) {
        this.seqName = seqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_seq.SEQ_VALUE
     *
     * @return the value of ms_seq.SEQ_VALUE
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public Integer getSeqValue() {
        return seqValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_seq.SEQ_VALUE
     *
     * @param seqValue the value for ms_seq.SEQ_VALUE
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public void setSeqValue(Integer seqValue) {
        this.seqValue = seqValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_seq.REGISTER_ID
     *
     * @return the value of ms_seq.REGISTER_ID
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public String getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_seq.REGISTER_ID
     *
     * @param registerId the value for ms_seq.REGISTER_ID
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public void setRegisterId(String registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_seq.REGISTER_DATIME
     *
     * @return the value of ms_seq.REGISTER_DATIME
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public Date getRegisterDatime() {
        return registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_seq.REGISTER_DATIME
     *
     * @param registerDatime the value for ms_seq.REGISTER_DATIME
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public void setRegisterDatime(Date registerDatime) {
        this.registerDatime = registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_seq.UPDATE_ID
     *
     * @return the value of ms_seq.UPDATE_ID
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_seq.UPDATE_ID
     *
     * @param updateId the value for ms_seq.UPDATE_ID
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_seq.UPDATE_DATIME
     *
     * @return the value of ms_seq.UPDATE_DATIME
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public Date getUpdateDatime() {
        return updateDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_seq.UPDATE_DATIME
     *
     * @param updateDatime the value for ms_seq.UPDATE_DATIME
     *
     * @mbg.generated Sat Mar 24 16:59:59 JST 2018
     */
    public void setUpdateDatime(Date updateDatime) {
        this.updateDatime = updateDatime;
    }
}