package jp.co.pds.common.dao.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MsUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public MsUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserLastnameIsNull() {
            addCriterion("USER_LASTNAME is null");
            return (Criteria) this;
        }

        public Criteria andUserLastnameIsNotNull() {
            addCriterion("USER_LASTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserLastnameEqualTo(String value) {
            addCriterion("USER_LASTNAME =", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameNotEqualTo(String value) {
            addCriterion("USER_LASTNAME <>", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameGreaterThan(String value) {
            addCriterion("USER_LASTNAME >", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_LASTNAME >=", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameLessThan(String value) {
            addCriterion("USER_LASTNAME <", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameLessThanOrEqualTo(String value) {
            addCriterion("USER_LASTNAME <=", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameLike(String value) {
            addCriterion("USER_LASTNAME like", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameNotLike(String value) {
            addCriterion("USER_LASTNAME not like", value, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameIn(List<String> values) {
            addCriterion("USER_LASTNAME in", values, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameNotIn(List<String> values) {
            addCriterion("USER_LASTNAME not in", values, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameBetween(String value1, String value2) {
            addCriterion("USER_LASTNAME between", value1, value2, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserLastnameNotBetween(String value1, String value2) {
            addCriterion("USER_LASTNAME not between", value1, value2, "userLastname");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andMailAddrIsNull() {
            addCriterion("MAIL_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andMailAddrIsNotNull() {
            addCriterion("MAIL_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andMailAddrEqualTo(String value) {
            addCriterion("MAIL_ADDR =", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrNotEqualTo(String value) {
            addCriterion("MAIL_ADDR <>", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrGreaterThan(String value) {
            addCriterion("MAIL_ADDR >", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrGreaterThanOrEqualTo(String value) {
            addCriterion("MAIL_ADDR >=", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrLessThan(String value) {
            addCriterion("MAIL_ADDR <", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrLessThanOrEqualTo(String value) {
            addCriterion("MAIL_ADDR <=", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrLike(String value) {
            addCriterion("MAIL_ADDR like", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrNotLike(String value) {
            addCriterion("MAIL_ADDR not like", value, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrIn(List<String> values) {
            addCriterion("MAIL_ADDR in", values, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrNotIn(List<String> values) {
            addCriterion("MAIL_ADDR not in", values, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrBetween(String value1, String value2) {
            addCriterion("MAIL_ADDR between", value1, value2, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andMailAddrNotBetween(String value1, String value2) {
            addCriterion("MAIL_ADDR not between", value1, value2, "mailAddr");
            return (Criteria) this;
        }

        public Criteria andPswdSeqIsNull() {
            addCriterion("PSWD_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andPswdSeqIsNotNull() {
            addCriterion("PSWD_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andPswdSeqEqualTo(Integer value) {
            addCriterion("PSWD_SEQ =", value, "pswdSeq");
            return (Criteria) this;
        }

        public Criteria andPswdSeqNotEqualTo(Integer value) {
            addCriterion("PSWD_SEQ <>", value, "pswdSeq");
            return (Criteria) this;
        }

        public Criteria andPswdSeqGreaterThan(Integer value) {
            addCriterion("PSWD_SEQ >", value, "pswdSeq");
            return (Criteria) this;
        }

        public Criteria andPswdSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("PSWD_SEQ >=", value, "pswdSeq");
            return (Criteria) this;
        }

        public Criteria andPswdSeqLessThan(Integer value) {
            addCriterion("PSWD_SEQ <", value, "pswdSeq");
            return (Criteria) this;
        }

        public Criteria andPswdSeqLessThanOrEqualTo(Integer value) {
            addCriterion("PSWD_SEQ <=", value, "pswdSeq");
            return (Criteria) this;
        }

        public Criteria andPswdSeqIn(List<Integer> values) {
            addCriterion("PSWD_SEQ in", values, "pswdSeq");
            return (Criteria) this;
        }

        public Criteria andPswdSeqNotIn(List<Integer> values) {
            addCriterion("PSWD_SEQ not in", values, "pswdSeq");
            return (Criteria) this;
        }

        public Criteria andPswdSeqBetween(Integer value1, Integer value2) {
            addCriterion("PSWD_SEQ between", value1, value2, "pswdSeq");
            return (Criteria) this;
        }

        public Criteria andPswdSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("PSWD_SEQ not between", value1, value2, "pswdSeq");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntIsNull() {
            addCriterion("LOGIN_TRIAL_CNT is null");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntIsNotNull() {
            addCriterion("LOGIN_TRIAL_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntEqualTo(Integer value) {
            addCriterion("LOGIN_TRIAL_CNT =", value, "loginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntNotEqualTo(Integer value) {
            addCriterion("LOGIN_TRIAL_CNT <>", value, "loginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntGreaterThan(Integer value) {
            addCriterion("LOGIN_TRIAL_CNT >", value, "loginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("LOGIN_TRIAL_CNT >=", value, "loginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntLessThan(Integer value) {
            addCriterion("LOGIN_TRIAL_CNT <", value, "loginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntLessThanOrEqualTo(Integer value) {
            addCriterion("LOGIN_TRIAL_CNT <=", value, "loginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntIn(List<Integer> values) {
            addCriterion("LOGIN_TRIAL_CNT in", values, "loginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntNotIn(List<Integer> values) {
            addCriterion("LOGIN_TRIAL_CNT not in", values, "loginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntBetween(Integer value1, Integer value2) {
            addCriterion("LOGIN_TRIAL_CNT between", value1, value2, "loginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andLoginTrialCntNotBetween(Integer value1, Integer value2) {
            addCriterion("LOGIN_TRIAL_CNT not between", value1, value2, "loginTrialCnt");
            return (Criteria) this;
        }

        public Criteria andLockFlgIsNull() {
            addCriterion("LOCK_FLG is null");
            return (Criteria) this;
        }

        public Criteria andLockFlgIsNotNull() {
            addCriterion("LOCK_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andLockFlgEqualTo(String value) {
            addCriterion("LOCK_FLG =", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgNotEqualTo(String value) {
            addCriterion("LOCK_FLG <>", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgGreaterThan(String value) {
            addCriterion("LOCK_FLG >", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgGreaterThanOrEqualTo(String value) {
            addCriterion("LOCK_FLG >=", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgLessThan(String value) {
            addCriterion("LOCK_FLG <", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgLessThanOrEqualTo(String value) {
            addCriterion("LOCK_FLG <=", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgLike(String value) {
            addCriterion("LOCK_FLG like", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgNotLike(String value) {
            addCriterion("LOCK_FLG not like", value, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgIn(List<String> values) {
            addCriterion("LOCK_FLG in", values, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgNotIn(List<String> values) {
            addCriterion("LOCK_FLG not in", values, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgBetween(String value1, String value2) {
            addCriterion("LOCK_FLG between", value1, value2, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andLockFlgNotBetween(String value1, String value2) {
            addCriterion("LOCK_FLG not between", value1, value2, "lockFlg");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdIsNull() {
            addCriterion("PSWD_UPDATE_DD is null");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdIsNotNull() {
            addCriterion("PSWD_UPDATE_DD is not null");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdEqualTo(Date value) {
            addCriterionForJDBCDate("PSWD_UPDATE_DD =", value, "pswdUpdateDd");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdNotEqualTo(Date value) {
            addCriterionForJDBCDate("PSWD_UPDATE_DD <>", value, "pswdUpdateDd");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdGreaterThan(Date value) {
            addCriterionForJDBCDate("PSWD_UPDATE_DD >", value, "pswdUpdateDd");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PSWD_UPDATE_DD >=", value, "pswdUpdateDd");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdLessThan(Date value) {
            addCriterionForJDBCDate("PSWD_UPDATE_DD <", value, "pswdUpdateDd");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PSWD_UPDATE_DD <=", value, "pswdUpdateDd");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdIn(List<Date> values) {
            addCriterionForJDBCDate("PSWD_UPDATE_DD in", values, "pswdUpdateDd");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdNotIn(List<Date> values) {
            addCriterionForJDBCDate("PSWD_UPDATE_DD not in", values, "pswdUpdateDd");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PSWD_UPDATE_DD between", value1, value2, "pswdUpdateDd");
            return (Criteria) this;
        }

        public Criteria andPswdUpdateDdNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PSWD_UPDATE_DD not between", value1, value2, "pswdUpdateDd");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("DELETE_FLG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("DELETE_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(String value) {
            addCriterion("DELETE_FLG =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(String value) {
            addCriterion("DELETE_FLG <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(String value) {
            addCriterion("DELETE_FLG >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(String value) {
            addCriterion("DELETE_FLG >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(String value) {
            addCriterion("DELETE_FLG <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(String value) {
            addCriterion("DELETE_FLG <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLike(String value) {
            addCriterion("DELETE_FLG like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotLike(String value) {
            addCriterion("DELETE_FLG not like", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<String> values) {
            addCriterion("DELETE_FLG in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<String> values) {
            addCriterion("DELETE_FLG not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(String value1, String value2) {
            addCriterion("DELETE_FLG between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(String value1, String value2) {
            addCriterion("DELETE_FLG not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNull() {
            addCriterion("REGISTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNotNull() {
            addCriterion("REGISTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdEqualTo(String value) {
            addCriterion("REGISTER_ID =", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotEqualTo(String value) {
            addCriterion("REGISTER_ID <>", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThan(String value) {
            addCriterion("REGISTER_ID >", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID >=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThan(String value) {
            addCriterion("REGISTER_ID <", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID <=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLike(String value) {
            addCriterion("REGISTER_ID like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotLike(String value) {
            addCriterion("REGISTER_ID not like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIn(List<String> values) {
            addCriterion("REGISTER_ID in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotIn(List<String> values) {
            addCriterion("REGISTER_ID not in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdBetween(String value1, String value2) {
            addCriterion("REGISTER_ID between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotBetween(String value1, String value2) {
            addCriterion("REGISTER_ID not between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNull() {
            addCriterion("REGISTER_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNotNull() {
            addCriterion("REGISTER_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeEqualTo(Date value) {
            addCriterion("REGISTER_DATIME =", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <>", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThan(Date value) {
            addCriterion("REGISTER_DATIME >", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME >=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThan(Date value) {
            addCriterion("REGISTER_DATIME <", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIn(List<Date> values) {
            addCriterion("REGISTER_DATIME in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotIn(List<Date> values) {
            addCriterion("REGISTER_DATIME not in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME not between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("UPDATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("UPDATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(String value) {
            addCriterion("UPDATE_ID =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(String value) {
            addCriterion("UPDATE_ID <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(String value) {
            addCriterion("UPDATE_ID >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(String value) {
            addCriterion("UPDATE_ID <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLike(String value) {
            addCriterion("UPDATE_ID like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotLike(String value) {
            addCriterion("UPDATE_ID not like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<String> values) {
            addCriterion("UPDATE_ID in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<String> values) {
            addCriterion("UPDATE_ID not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(String value1, String value2) {
            addCriterion("UPDATE_ID between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_ID not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNull() {
            addCriterion("UPDATE_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNotNull() {
            addCriterion("UPDATE_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeEqualTo(Date value) {
            addCriterion("UPDATE_DATIME =", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <>", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThan(Date value) {
            addCriterion("UPDATE_DATIME >", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME >=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThan(Date value) {
            addCriterion("UPDATE_DATIME <", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIn(List<Date> values) {
            addCriterion("UPDATE_DATIME in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotIn(List<Date> values) {
            addCriterion("UPDATE_DATIME not in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME between", value1, value2, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME not between", value1, value2, "updateDatime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_user
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 17 22:24:13 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_user
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}