package jp.co.pds.common.dao.dto;

import java.util.Date;

public class MsUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.USER_ID
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.USER_LASTNAME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private String userLastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.USER_NAME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.MAIL_ADDR
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private String mailAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.PSWD_SEQ
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private Integer pswdSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.LOGIN_TRIAL_CNT
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private Integer loginTrialCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.LOCK_FLG
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private String lockFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.PSWD_UPDATE_DD
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private Date pswdUpdateDd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.DELETE_FLG
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private String deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.REGISTER_ID
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private String registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.REGISTER_DATIME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private Date registerDatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.UPDATE_ID
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.UPDATE_DATIME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    private Date updateDatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.USER_ID
     *
     * @return the value of ms_user.USER_ID
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.USER_ID
     *
     * @param userId the value for ms_user.USER_ID
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.USER_LASTNAME
     *
     * @return the value of ms_user.USER_LASTNAME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public String getUserLastname() {
        return userLastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.USER_LASTNAME
     *
     * @param userLastname the value for ms_user.USER_LASTNAME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setUserLastname(String userLastname) {
        this.userLastname = userLastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.USER_NAME
     *
     * @return the value of ms_user.USER_NAME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.USER_NAME
     *
     * @param userName the value for ms_user.USER_NAME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.MAIL_ADDR
     *
     * @return the value of ms_user.MAIL_ADDR
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public String getMailAddr() {
        return mailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.MAIL_ADDR
     *
     * @param mailAddr the value for ms_user.MAIL_ADDR
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setMailAddr(String mailAddr) {
        this.mailAddr = mailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.PSWD_SEQ
     *
     * @return the value of ms_user.PSWD_SEQ
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public Integer getPswdSeq() {
        return pswdSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.PSWD_SEQ
     *
     * @param pswdSeq the value for ms_user.PSWD_SEQ
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setPswdSeq(Integer pswdSeq) {
        this.pswdSeq = pswdSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.LOGIN_TRIAL_CNT
     *
     * @return the value of ms_user.LOGIN_TRIAL_CNT
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public Integer getLoginTrialCnt() {
        return loginTrialCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.LOGIN_TRIAL_CNT
     *
     * @param loginTrialCnt the value for ms_user.LOGIN_TRIAL_CNT
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setLoginTrialCnt(Integer loginTrialCnt) {
        this.loginTrialCnt = loginTrialCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.LOCK_FLG
     *
     * @return the value of ms_user.LOCK_FLG
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public String getLockFlg() {
        return lockFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.LOCK_FLG
     *
     * @param lockFlg the value for ms_user.LOCK_FLG
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setLockFlg(String lockFlg) {
        this.lockFlg = lockFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.PSWD_UPDATE_DD
     *
     * @return the value of ms_user.PSWD_UPDATE_DD
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public Date getPswdUpdateDd() {
        return pswdUpdateDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.PSWD_UPDATE_DD
     *
     * @param pswdUpdateDd the value for ms_user.PSWD_UPDATE_DD
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setPswdUpdateDd(Date pswdUpdateDd) {
        this.pswdUpdateDd = pswdUpdateDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.DELETE_FLG
     *
     * @return the value of ms_user.DELETE_FLG
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.DELETE_FLG
     *
     * @param deleteFlg the value for ms_user.DELETE_FLG
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.REGISTER_ID
     *
     * @return the value of ms_user.REGISTER_ID
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public String getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.REGISTER_ID
     *
     * @param registerId the value for ms_user.REGISTER_ID
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setRegisterId(String registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.REGISTER_DATIME
     *
     * @return the value of ms_user.REGISTER_DATIME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public Date getRegisterDatime() {
        return registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.REGISTER_DATIME
     *
     * @param registerDatime the value for ms_user.REGISTER_DATIME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setRegisterDatime(Date registerDatime) {
        this.registerDatime = registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.UPDATE_ID
     *
     * @return the value of ms_user.UPDATE_ID
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.UPDATE_ID
     *
     * @param updateId the value for ms_user.UPDATE_ID
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.UPDATE_DATIME
     *
     * @return the value of ms_user.UPDATE_DATIME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public Date getUpdateDatime() {
        return updateDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.UPDATE_DATIME
     *
     * @param updateDatime the value for ms_user.UPDATE_DATIME
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    public void setUpdateDatime(Date updateDatime) {
        this.updateDatime = updateDatime;
    }
}