package jp.co.pds.common.dao.mapper;

import java.util.List;
import jp.co.pds.common.dao.dto.DtPswdHistory;
import jp.co.pds.common.dao.dto.DtPswdHistoryExample;
import jp.co.pds.common.dao.dto.DtPswdHistoryKey;
import org.apache.ibatis.annotations.Param;

public interface DtPswdHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    long countByExample(DtPswdHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    int deleteByExample(DtPswdHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    int deleteByPrimaryKey(DtPswdHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    int insert(DtPswdHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    int insertSelective(DtPswdHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    List<DtPswdHistory> selectByExample(DtPswdHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    DtPswdHistory selectByPrimaryKey(DtPswdHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    int updateByExampleSelective(@Param("record") DtPswdHistory record, @Param("example") DtPswdHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    int updateByExample(@Param("record") DtPswdHistory record, @Param("example") DtPswdHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    int updateByPrimaryKeySelective(DtPswdHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_pswd_history
     *
     * @mbg.generated Sat Mar 17 22:24:13 JST 2018
     */
    int updateByPrimaryKey(DtPswdHistory record);
}