package jp.co.pds.common.dao.mapper;

import java.util.List;
import jp.co.pds.common.dao.dto.MsCompanyGroup;
import jp.co.pds.common.dao.dto.MsCompanyGroupExample;
import jp.co.pds.common.dao.dto.MsCompanyGroupKey;
import org.apache.ibatis.annotations.Param;

public interface MsCompanyGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    long countByExample(MsCompanyGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    int deleteByExample(MsCompanyGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    int deleteByPrimaryKey(MsCompanyGroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    int insert(MsCompanyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    int insertSelective(MsCompanyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    List<MsCompanyGroup> selectByExample(MsCompanyGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    MsCompanyGroup selectByPrimaryKey(MsCompanyGroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    int updateByExampleSelective(@Param("record") MsCompanyGroup record, @Param("example") MsCompanyGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    int updateByExample(@Param("record") MsCompanyGroup record, @Param("example") MsCompanyGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    int updateByPrimaryKeySelective(MsCompanyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_company_group
     *
     * @mbg.generated Sat Apr 21 03:22:25 JST 2018
     */
    int updateByPrimaryKey(MsCompanyGroup record);
}