package jp.co.pds.common.dao.mapper;

import java.util.List;
import jp.co.pds.common.dao.dto.MsDate;
import jp.co.pds.common.dao.dto.MsDateExample;
import jp.co.pds.common.dao.dto.MsDateKey;
import org.apache.ibatis.annotations.Param;

public interface MsDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    long countByExample(MsDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int deleteByExample(MsDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int deleteByPrimaryKey(MsDateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int insert(MsDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int insertSelective(MsDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    List<MsDate> selectByExample(MsDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    MsDate selectByPrimaryKey(MsDateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int updateByExampleSelective(@Param("record") MsDate record, @Param("example") MsDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int updateByExample(@Param("record") MsDate record, @Param("example") MsDateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int updateByPrimaryKeySelective(MsDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_date
     *
     * @mbg.generated Sun Apr 08 08:38:07 JST 2018
     */
    int updateByPrimaryKey(MsDate record);
}