package jp.co.pds.common.dao.mapper;

import java.util.List;
import jp.co.pds.common.dao.dto.MsGroup;
import jp.co.pds.common.dao.dto.MsGroupExample;
import org.apache.ibatis.annotations.Param;

public interface MsGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    long countByExample(MsGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    int deleteByExample(MsGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    int insert(MsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    int insertSelective(MsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    List<MsGroup> selectByExample(MsGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    MsGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    int updateByExampleSelective(@Param("record") MsGroup record, @Param("example") MsGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    int updateByExample(@Param("record") MsGroup record, @Param("example") MsGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    int updateByPrimaryKeySelective(MsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group
     *
     * @mbg.generated Thu Apr 12 22:44:55 JST 2018
     */
    int updateByPrimaryKey(MsGroup record);
}