package jp.co.pds.common.dao.mapper;

import java.util.List;
import jp.co.pds.common.dao.dto.MsGroupUser;
import jp.co.pds.common.dao.dto.MsGroupUserExample;
import jp.co.pds.common.dao.dto.MsGroupUserKey;
import org.apache.ibatis.annotations.Param;

public interface MsGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    long countByExample(MsGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    int deleteByExample(MsGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    int deleteByPrimaryKey(MsGroupUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    int insert(MsGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    int insertSelective(MsGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    List<MsGroupUser> selectByExample(MsGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    MsGroupUser selectByPrimaryKey(MsGroupUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    int updateByExampleSelective(@Param("record") MsGroupUser record, @Param("example") MsGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    int updateByExample(@Param("record") MsGroupUser record, @Param("example") MsGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    int updateByPrimaryKeySelective(MsGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_group_user
     *
     * @mbg.generated Mon Mar 19 15:00:53 JST 2018
     */
    int updateByPrimaryKey(MsGroupUser record);
}