package jp.co.pds.PJ0002.dao.dto;

import java.util.Date;

public class DtExpenseAdjstmnt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.EXPENSE_ADJSTMNT_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private Integer expenseAdjstmntId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.COMPANY_CD
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private String companyCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.USER_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.ACCOUNT_TITLE_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private Integer accountTitleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.CALENDAR_YY
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private Integer calendarYy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.CALENDAR_MM
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private Integer calendarMm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.CALENDAR_DD
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private Integer calendarDd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.EXPENSE_AMOUNT
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private Integer expenseAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.TEMPORARY_MONEY
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private Integer temporaryMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.REMARK
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.REGISTER_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private String registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.REGISTER_DATIME
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private Date registerDatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.UPDATE_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_expense_adjstmnt.UPDATE_DATIME
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    private Date updateDatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.EXPENSE_ADJSTMNT_ID
     *
     * @return the value of dt_expense_adjstmnt.EXPENSE_ADJSTMNT_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Integer getExpenseAdjstmntId() {
        return expenseAdjstmntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.EXPENSE_ADJSTMNT_ID
     *
     * @param expenseAdjstmntId the value for dt_expense_adjstmnt.EXPENSE_ADJSTMNT_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setExpenseAdjstmntId(Integer expenseAdjstmntId) {
        this.expenseAdjstmntId = expenseAdjstmntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.COMPANY_CD
     *
     * @return the value of dt_expense_adjstmnt.COMPANY_CD
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public String getCompanyCd() {
        return companyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.COMPANY_CD
     *
     * @param companyCd the value for dt_expense_adjstmnt.COMPANY_CD
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setCompanyCd(String companyCd) {
        this.companyCd = companyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.USER_ID
     *
     * @return the value of dt_expense_adjstmnt.USER_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.USER_ID
     *
     * @param userId the value for dt_expense_adjstmnt.USER_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.ACCOUNT_TITLE_ID
     *
     * @return the value of dt_expense_adjstmnt.ACCOUNT_TITLE_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Integer getAccountTitleId() {
        return accountTitleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.ACCOUNT_TITLE_ID
     *
     * @param accountTitleId the value for dt_expense_adjstmnt.ACCOUNT_TITLE_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setAccountTitleId(Integer accountTitleId) {
        this.accountTitleId = accountTitleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.CALENDAR_YY
     *
     * @return the value of dt_expense_adjstmnt.CALENDAR_YY
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Integer getCalendarYy() {
        return calendarYy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.CALENDAR_YY
     *
     * @param calendarYy the value for dt_expense_adjstmnt.CALENDAR_YY
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setCalendarYy(Integer calendarYy) {
        this.calendarYy = calendarYy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.CALENDAR_MM
     *
     * @return the value of dt_expense_adjstmnt.CALENDAR_MM
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Integer getCalendarMm() {
        return calendarMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.CALENDAR_MM
     *
     * @param calendarMm the value for dt_expense_adjstmnt.CALENDAR_MM
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setCalendarMm(Integer calendarMm) {
        this.calendarMm = calendarMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.CALENDAR_DD
     *
     * @return the value of dt_expense_adjstmnt.CALENDAR_DD
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Integer getCalendarDd() {
        return calendarDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.CALENDAR_DD
     *
     * @param calendarDd the value for dt_expense_adjstmnt.CALENDAR_DD
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setCalendarDd(Integer calendarDd) {
        this.calendarDd = calendarDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.EXPENSE_AMOUNT
     *
     * @return the value of dt_expense_adjstmnt.EXPENSE_AMOUNT
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Integer getExpenseAmount() {
        return expenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.EXPENSE_AMOUNT
     *
     * @param expenseAmount the value for dt_expense_adjstmnt.EXPENSE_AMOUNT
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setExpenseAmount(Integer expenseAmount) {
        this.expenseAmount = expenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.TEMPORARY_MONEY
     *
     * @return the value of dt_expense_adjstmnt.TEMPORARY_MONEY
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Integer getTemporaryMoney() {
        return temporaryMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.TEMPORARY_MONEY
     *
     * @param temporaryMoney the value for dt_expense_adjstmnt.TEMPORARY_MONEY
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setTemporaryMoney(Integer temporaryMoney) {
        this.temporaryMoney = temporaryMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.REMARK
     *
     * @return the value of dt_expense_adjstmnt.REMARK
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.REMARK
     *
     * @param remark the value for dt_expense_adjstmnt.REMARK
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.REGISTER_ID
     *
     * @return the value of dt_expense_adjstmnt.REGISTER_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public String getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.REGISTER_ID
     *
     * @param registerId the value for dt_expense_adjstmnt.REGISTER_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setRegisterId(String registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.REGISTER_DATIME
     *
     * @return the value of dt_expense_adjstmnt.REGISTER_DATIME
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Date getRegisterDatime() {
        return registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.REGISTER_DATIME
     *
     * @param registerDatime the value for dt_expense_adjstmnt.REGISTER_DATIME
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setRegisterDatime(Date registerDatime) {
        this.registerDatime = registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.UPDATE_ID
     *
     * @return the value of dt_expense_adjstmnt.UPDATE_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.UPDATE_ID
     *
     * @param updateId the value for dt_expense_adjstmnt.UPDATE_ID
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_expense_adjstmnt.UPDATE_DATIME
     *
     * @return the value of dt_expense_adjstmnt.UPDATE_DATIME
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Date getUpdateDatime() {
        return updateDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_expense_adjstmnt.UPDATE_DATIME
     *
     * @param updateDatime the value for dt_expense_adjstmnt.UPDATE_DATIME
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setUpdateDatime(Date updateDatime) {
        this.updateDatime = updateDatime;
    }
}