package jp.co.pds.PJ0002.dao.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DtExpenseAdjstmntExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public DtExpenseAdjstmntExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andExpenseAdjstmntIdIsNull() {
            addCriterion("EXPENSE_ADJSTMNT_ID is null");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdIsNotNull() {
            addCriterion("EXPENSE_ADJSTMNT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdEqualTo(Integer value) {
            addCriterion("EXPENSE_ADJSTMNT_ID =", value, "expenseAdjstmntId");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdNotEqualTo(Integer value) {
            addCriterion("EXPENSE_ADJSTMNT_ID <>", value, "expenseAdjstmntId");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdGreaterThan(Integer value) {
            addCriterion("EXPENSE_ADJSTMNT_ID >", value, "expenseAdjstmntId");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("EXPENSE_ADJSTMNT_ID >=", value, "expenseAdjstmntId");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdLessThan(Integer value) {
            addCriterion("EXPENSE_ADJSTMNT_ID <", value, "expenseAdjstmntId");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdLessThanOrEqualTo(Integer value) {
            addCriterion("EXPENSE_ADJSTMNT_ID <=", value, "expenseAdjstmntId");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdIn(List<Integer> values) {
            addCriterion("EXPENSE_ADJSTMNT_ID in", values, "expenseAdjstmntId");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdNotIn(List<Integer> values) {
            addCriterion("EXPENSE_ADJSTMNT_ID not in", values, "expenseAdjstmntId");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdBetween(Integer value1, Integer value2) {
            addCriterion("EXPENSE_ADJSTMNT_ID between", value1, value2, "expenseAdjstmntId");
            return (Criteria) this;
        }

        public Criteria andExpenseAdjstmntIdNotBetween(Integer value1, Integer value2) {
            addCriterion("EXPENSE_ADJSTMNT_ID not between", value1, value2, "expenseAdjstmntId");
            return (Criteria) this;
        }

        public Criteria andCompanyCdIsNull() {
            addCriterion("COMPANY_CD is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCdIsNotNull() {
            addCriterion("COMPANY_CD is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCdEqualTo(String value) {
            addCriterion("COMPANY_CD =", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdNotEqualTo(String value) {
            addCriterion("COMPANY_CD <>", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdGreaterThan(String value) {
            addCriterion("COMPANY_CD >", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_CD >=", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdLessThan(String value) {
            addCriterion("COMPANY_CD <", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_CD <=", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdLike(String value) {
            addCriterion("COMPANY_CD like", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdNotLike(String value) {
            addCriterion("COMPANY_CD not like", value, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdIn(List<String> values) {
            addCriterion("COMPANY_CD in", values, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdNotIn(List<String> values) {
            addCriterion("COMPANY_CD not in", values, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdBetween(String value1, String value2) {
            addCriterion("COMPANY_CD between", value1, value2, "companyCd");
            return (Criteria) this;
        }

        public Criteria andCompanyCdNotBetween(String value1, String value2) {
            addCriterion("COMPANY_CD not between", value1, value2, "companyCd");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdIsNull() {
            addCriterion("ACCOUNT_TITLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdIsNotNull() {
            addCriterion("ACCOUNT_TITLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdEqualTo(Integer value) {
            addCriterion("ACCOUNT_TITLE_ID =", value, "accountTitleId");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdNotEqualTo(Integer value) {
            addCriterion("ACCOUNT_TITLE_ID <>", value, "accountTitleId");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdGreaterThan(Integer value) {
            addCriterion("ACCOUNT_TITLE_ID >", value, "accountTitleId");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACCOUNT_TITLE_ID >=", value, "accountTitleId");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdLessThan(Integer value) {
            addCriterion("ACCOUNT_TITLE_ID <", value, "accountTitleId");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdLessThanOrEqualTo(Integer value) {
            addCriterion("ACCOUNT_TITLE_ID <=", value, "accountTitleId");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdIn(List<Integer> values) {
            addCriterion("ACCOUNT_TITLE_ID in", values, "accountTitleId");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdNotIn(List<Integer> values) {
            addCriterion("ACCOUNT_TITLE_ID not in", values, "accountTitleId");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdBetween(Integer value1, Integer value2) {
            addCriterion("ACCOUNT_TITLE_ID between", value1, value2, "accountTitleId");
            return (Criteria) this;
        }

        public Criteria andAccountTitleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ACCOUNT_TITLE_ID not between", value1, value2, "accountTitleId");
            return (Criteria) this;
        }

        public Criteria andCalendarYyIsNull() {
            addCriterion("CALENDAR_YY is null");
            return (Criteria) this;
        }

        public Criteria andCalendarYyIsNotNull() {
            addCriterion("CALENDAR_YY is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarYyEqualTo(Integer value) {
            addCriterion("CALENDAR_YY =", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyNotEqualTo(Integer value) {
            addCriterion("CALENDAR_YY <>", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyGreaterThan(Integer value) {
            addCriterion("CALENDAR_YY >", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyGreaterThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_YY >=", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyLessThan(Integer value) {
            addCriterion("CALENDAR_YY <", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyLessThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_YY <=", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyIn(List<Integer> values) {
            addCriterion("CALENDAR_YY in", values, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyNotIn(List<Integer> values) {
            addCriterion("CALENDAR_YY not in", values, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_YY between", value1, value2, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyNotBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_YY not between", value1, value2, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarMmIsNull() {
            addCriterion("CALENDAR_MM is null");
            return (Criteria) this;
        }

        public Criteria andCalendarMmIsNotNull() {
            addCriterion("CALENDAR_MM is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarMmEqualTo(Integer value) {
            addCriterion("CALENDAR_MM =", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmNotEqualTo(Integer value) {
            addCriterion("CALENDAR_MM <>", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmGreaterThan(Integer value) {
            addCriterion("CALENDAR_MM >", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmGreaterThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_MM >=", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmLessThan(Integer value) {
            addCriterion("CALENDAR_MM <", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmLessThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_MM <=", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmIn(List<Integer> values) {
            addCriterion("CALENDAR_MM in", values, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmNotIn(List<Integer> values) {
            addCriterion("CALENDAR_MM not in", values, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_MM between", value1, value2, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmNotBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_MM not between", value1, value2, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarDdIsNull() {
            addCriterion("CALENDAR_DD is null");
            return (Criteria) this;
        }

        public Criteria andCalendarDdIsNotNull() {
            addCriterion("CALENDAR_DD is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarDdEqualTo(Integer value) {
            addCriterion("CALENDAR_DD =", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdNotEqualTo(Integer value) {
            addCriterion("CALENDAR_DD <>", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdGreaterThan(Integer value) {
            addCriterion("CALENDAR_DD >", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_DD >=", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdLessThan(Integer value) {
            addCriterion("CALENDAR_DD <", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdLessThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_DD <=", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdIn(List<Integer> values) {
            addCriterion("CALENDAR_DD in", values, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdNotIn(List<Integer> values) {
            addCriterion("CALENDAR_DD not in", values, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_DD between", value1, value2, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdNotBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_DD not between", value1, value2, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountIsNull() {
            addCriterion("EXPENSE_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountIsNotNull() {
            addCriterion("EXPENSE_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountEqualTo(Integer value) {
            addCriterion("EXPENSE_AMOUNT =", value, "expenseAmount");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountNotEqualTo(Integer value) {
            addCriterion("EXPENSE_AMOUNT <>", value, "expenseAmount");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountGreaterThan(Integer value) {
            addCriterion("EXPENSE_AMOUNT >", value, "expenseAmount");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("EXPENSE_AMOUNT >=", value, "expenseAmount");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountLessThan(Integer value) {
            addCriterion("EXPENSE_AMOUNT <", value, "expenseAmount");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountLessThanOrEqualTo(Integer value) {
            addCriterion("EXPENSE_AMOUNT <=", value, "expenseAmount");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountIn(List<Integer> values) {
            addCriterion("EXPENSE_AMOUNT in", values, "expenseAmount");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountNotIn(List<Integer> values) {
            addCriterion("EXPENSE_AMOUNT not in", values, "expenseAmount");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountBetween(Integer value1, Integer value2) {
            addCriterion("EXPENSE_AMOUNT between", value1, value2, "expenseAmount");
            return (Criteria) this;
        }

        public Criteria andExpenseAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("EXPENSE_AMOUNT not between", value1, value2, "expenseAmount");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyIsNull() {
            addCriterion("TEMPORARY_MONEY is null");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyIsNotNull() {
            addCriterion("TEMPORARY_MONEY is not null");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyEqualTo(Integer value) {
            addCriterion("TEMPORARY_MONEY =", value, "temporaryMoney");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyNotEqualTo(Integer value) {
            addCriterion("TEMPORARY_MONEY <>", value, "temporaryMoney");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyGreaterThan(Integer value) {
            addCriterion("TEMPORARY_MONEY >", value, "temporaryMoney");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("TEMPORARY_MONEY >=", value, "temporaryMoney");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyLessThan(Integer value) {
            addCriterion("TEMPORARY_MONEY <", value, "temporaryMoney");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyLessThanOrEqualTo(Integer value) {
            addCriterion("TEMPORARY_MONEY <=", value, "temporaryMoney");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyIn(List<Integer> values) {
            addCriterion("TEMPORARY_MONEY in", values, "temporaryMoney");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyNotIn(List<Integer> values) {
            addCriterion("TEMPORARY_MONEY not in", values, "temporaryMoney");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyBetween(Integer value1, Integer value2) {
            addCriterion("TEMPORARY_MONEY between", value1, value2, "temporaryMoney");
            return (Criteria) this;
        }

        public Criteria andTemporaryMoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("TEMPORARY_MONEY not between", value1, value2, "temporaryMoney");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNull() {
            addCriterion("REGISTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNotNull() {
            addCriterion("REGISTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdEqualTo(String value) {
            addCriterion("REGISTER_ID =", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotEqualTo(String value) {
            addCriterion("REGISTER_ID <>", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThan(String value) {
            addCriterion("REGISTER_ID >", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID >=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThan(String value) {
            addCriterion("REGISTER_ID <", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID <=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLike(String value) {
            addCriterion("REGISTER_ID like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotLike(String value) {
            addCriterion("REGISTER_ID not like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIn(List<String> values) {
            addCriterion("REGISTER_ID in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotIn(List<String> values) {
            addCriterion("REGISTER_ID not in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdBetween(String value1, String value2) {
            addCriterion("REGISTER_ID between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotBetween(String value1, String value2) {
            addCriterion("REGISTER_ID not between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNull() {
            addCriterion("REGISTER_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNotNull() {
            addCriterion("REGISTER_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeEqualTo(Date value) {
            addCriterion("REGISTER_DATIME =", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <>", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThan(Date value) {
            addCriterion("REGISTER_DATIME >", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME >=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThan(Date value) {
            addCriterion("REGISTER_DATIME <", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIn(List<Date> values) {
            addCriterion("REGISTER_DATIME in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotIn(List<Date> values) {
            addCriterion("REGISTER_DATIME not in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME not between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("UPDATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("UPDATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(String value) {
            addCriterion("UPDATE_ID =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(String value) {
            addCriterion("UPDATE_ID <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(String value) {
            addCriterion("UPDATE_ID >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(String value) {
            addCriterion("UPDATE_ID <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLike(String value) {
            addCriterion("UPDATE_ID like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotLike(String value) {
            addCriterion("UPDATE_ID not like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<String> values) {
            addCriterion("UPDATE_ID in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<String> values) {
            addCriterion("UPDATE_ID not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(String value1, String value2) {
            addCriterion("UPDATE_ID between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_ID not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNull() {
            addCriterion("UPDATE_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNotNull() {
            addCriterion("UPDATE_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeEqualTo(Date value) {
            addCriterion("UPDATE_DATIME =", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <>", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThan(Date value) {
            addCriterion("UPDATE_DATIME >", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME >=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThan(Date value) {
            addCriterion("UPDATE_DATIME <", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIn(List<Date> values) {
            addCriterion("UPDATE_DATIME in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotIn(List<Date> values) {
            addCriterion("UPDATE_DATIME not in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME between", value1, value2, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME not between", value1, value2, "updateDatime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 09 21:26:09 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dt_expense_adjstmnt
     *
     * @mbg.generated Sat Jun 09 21:26:09 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}