package jp.co.pds.PJ0002.dao.dto;

import java.util.Date;

public class DtTransportExpense {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.TRANSPORT_EXPENSE_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private Integer transportExpenseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.COMPANY_CD
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private String companyCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.USER_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.CALENDAR_YY
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private Integer calendarYy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.CALENDAR_MM
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private Integer calendarMm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.CALENDAR_DD
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private Integer calendarDd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.EXPENSE_AMOUNT
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private Integer expenseAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.TEMPORARY_MONEY
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private Integer temporaryMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.DESTINATION
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private String destination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.BUSINESS
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private String business;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.TRANSPORT_FACILITY
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private String transportFacility;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.DEPARTURE
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private String departure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.ARRIVAL
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private String arrival;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.ONE_ROUND_CD
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private String oneRoundCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.REGISTER_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private String registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.REGISTER_DATIME
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private Date registerDatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.UPDATE_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dt_transport_expense.UPDATE_DATIME
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    private Date updateDatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.TRANSPORT_EXPENSE_ID
     *
     * @return the value of dt_transport_expense.TRANSPORT_EXPENSE_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public Integer getTransportExpenseId() {
        return transportExpenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.TRANSPORT_EXPENSE_ID
     *
     * @param transportExpenseId the value for dt_transport_expense.TRANSPORT_EXPENSE_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setTransportExpenseId(Integer transportExpenseId) {
        this.transportExpenseId = transportExpenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.COMPANY_CD
     *
     * @return the value of dt_transport_expense.COMPANY_CD
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public String getCompanyCd() {
        return companyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.COMPANY_CD
     *
     * @param companyCd the value for dt_transport_expense.COMPANY_CD
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setCompanyCd(String companyCd) {
        this.companyCd = companyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.USER_ID
     *
     * @return the value of dt_transport_expense.USER_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.USER_ID
     *
     * @param userId the value for dt_transport_expense.USER_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.CALENDAR_YY
     *
     * @return the value of dt_transport_expense.CALENDAR_YY
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public Integer getCalendarYy() {
        return calendarYy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.CALENDAR_YY
     *
     * @param calendarYy the value for dt_transport_expense.CALENDAR_YY
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setCalendarYy(Integer calendarYy) {
        this.calendarYy = calendarYy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.CALENDAR_MM
     *
     * @return the value of dt_transport_expense.CALENDAR_MM
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public Integer getCalendarMm() {
        return calendarMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.CALENDAR_MM
     *
     * @param calendarMm the value for dt_transport_expense.CALENDAR_MM
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setCalendarMm(Integer calendarMm) {
        this.calendarMm = calendarMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.CALENDAR_DD
     *
     * @return the value of dt_transport_expense.CALENDAR_DD
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public Integer getCalendarDd() {
        return calendarDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.CALENDAR_DD
     *
     * @param calendarDd the value for dt_transport_expense.CALENDAR_DD
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setCalendarDd(Integer calendarDd) {
        this.calendarDd = calendarDd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.EXPENSE_AMOUNT
     *
     * @return the value of dt_transport_expense.EXPENSE_AMOUNT
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public Integer getExpenseAmount() {
        return expenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.EXPENSE_AMOUNT
     *
     * @param expenseAmount the value for dt_transport_expense.EXPENSE_AMOUNT
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setExpenseAmount(Integer expenseAmount) {
        this.expenseAmount = expenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.TEMPORARY_MONEY
     *
     * @return the value of dt_transport_expense.TEMPORARY_MONEY
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public Integer getTemporaryMoney() {
        return temporaryMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.TEMPORARY_MONEY
     *
     * @param temporaryMoney the value for dt_transport_expense.TEMPORARY_MONEY
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setTemporaryMoney(Integer temporaryMoney) {
        this.temporaryMoney = temporaryMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.DESTINATION
     *
     * @return the value of dt_transport_expense.DESTINATION
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.DESTINATION
     *
     * @param destination the value for dt_transport_expense.DESTINATION
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.BUSINESS
     *
     * @return the value of dt_transport_expense.BUSINESS
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.BUSINESS
     *
     * @param business the value for dt_transport_expense.BUSINESS
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setBusiness(String business) {
        this.business = business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.TRANSPORT_FACILITY
     *
     * @return the value of dt_transport_expense.TRANSPORT_FACILITY
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public String getTransportFacility() {
        return transportFacility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.TRANSPORT_FACILITY
     *
     * @param transportFacility the value for dt_transport_expense.TRANSPORT_FACILITY
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setTransportFacility(String transportFacility) {
        this.transportFacility = transportFacility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.DEPARTURE
     *
     * @return the value of dt_transport_expense.DEPARTURE
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public String getDeparture() {
        return departure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.DEPARTURE
     *
     * @param departure the value for dt_transport_expense.DEPARTURE
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setDeparture(String departure) {
        this.departure = departure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.ARRIVAL
     *
     * @return the value of dt_transport_expense.ARRIVAL
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public String getArrival() {
        return arrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.ARRIVAL
     *
     * @param arrival the value for dt_transport_expense.ARRIVAL
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setArrival(String arrival) {
        this.arrival = arrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.ONE_ROUND_CD
     *
     * @return the value of dt_transport_expense.ONE_ROUND_CD
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public String getOneRoundCd() {
        return oneRoundCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.ONE_ROUND_CD
     *
     * @param oneRoundCd the value for dt_transport_expense.ONE_ROUND_CD
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setOneRoundCd(String oneRoundCd) {
        this.oneRoundCd = oneRoundCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.REGISTER_ID
     *
     * @return the value of dt_transport_expense.REGISTER_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public String getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.REGISTER_ID
     *
     * @param registerId the value for dt_transport_expense.REGISTER_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setRegisterId(String registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.REGISTER_DATIME
     *
     * @return the value of dt_transport_expense.REGISTER_DATIME
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public Date getRegisterDatime() {
        return registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.REGISTER_DATIME
     *
     * @param registerDatime the value for dt_transport_expense.REGISTER_DATIME
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setRegisterDatime(Date registerDatime) {
        this.registerDatime = registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.UPDATE_ID
     *
     * @return the value of dt_transport_expense.UPDATE_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.UPDATE_ID
     *
     * @param updateId the value for dt_transport_expense.UPDATE_ID
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dt_transport_expense.UPDATE_DATIME
     *
     * @return the value of dt_transport_expense.UPDATE_DATIME
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public Date getUpdateDatime() {
        return updateDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dt_transport_expense.UPDATE_DATIME
     *
     * @param updateDatime the value for dt_transport_expense.UPDATE_DATIME
     *
     * @mbg.generated Tue Apr 24 22:43:53 JST 2018
     */
    public void setUpdateDatime(Date updateDatime) {
        this.updateDatime = updateDatime;
    }
}