package jp.co.pds.PJ0002.dao.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DtWorkTimeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public DtWorkTimeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCalendarYyIsNull() {
            addCriterion("CALENDAR_YY is null");
            return (Criteria) this;
        }

        public Criteria andCalendarYyIsNotNull() {
            addCriterion("CALENDAR_YY is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarYyEqualTo(Integer value) {
            addCriterion("CALENDAR_YY =", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyNotEqualTo(Integer value) {
            addCriterion("CALENDAR_YY <>", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyGreaterThan(Integer value) {
            addCriterion("CALENDAR_YY >", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyGreaterThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_YY >=", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyLessThan(Integer value) {
            addCriterion("CALENDAR_YY <", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyLessThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_YY <=", value, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyIn(List<Integer> values) {
            addCriterion("CALENDAR_YY in", values, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyNotIn(List<Integer> values) {
            addCriterion("CALENDAR_YY not in", values, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_YY between", value1, value2, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarYyNotBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_YY not between", value1, value2, "calendarYy");
            return (Criteria) this;
        }

        public Criteria andCalendarMmIsNull() {
            addCriterion("CALENDAR_MM is null");
            return (Criteria) this;
        }

        public Criteria andCalendarMmIsNotNull() {
            addCriterion("CALENDAR_MM is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarMmEqualTo(Integer value) {
            addCriterion("CALENDAR_MM =", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmNotEqualTo(Integer value) {
            addCriterion("CALENDAR_MM <>", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmGreaterThan(Integer value) {
            addCriterion("CALENDAR_MM >", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmGreaterThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_MM >=", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmLessThan(Integer value) {
            addCriterion("CALENDAR_MM <", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmLessThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_MM <=", value, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmIn(List<Integer> values) {
            addCriterion("CALENDAR_MM in", values, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmNotIn(List<Integer> values) {
            addCriterion("CALENDAR_MM not in", values, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_MM between", value1, value2, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarMmNotBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_MM not between", value1, value2, "calendarMm");
            return (Criteria) this;
        }

        public Criteria andCalendarDdIsNull() {
            addCriterion("CALENDAR_DD is null");
            return (Criteria) this;
        }

        public Criteria andCalendarDdIsNotNull() {
            addCriterion("CALENDAR_DD is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarDdEqualTo(Integer value) {
            addCriterion("CALENDAR_DD =", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdNotEqualTo(Integer value) {
            addCriterion("CALENDAR_DD <>", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdGreaterThan(Integer value) {
            addCriterion("CALENDAR_DD >", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_DD >=", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdLessThan(Integer value) {
            addCriterion("CALENDAR_DD <", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdLessThanOrEqualTo(Integer value) {
            addCriterion("CALENDAR_DD <=", value, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdIn(List<Integer> values) {
            addCriterion("CALENDAR_DD in", values, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdNotIn(List<Integer> values) {
            addCriterion("CALENDAR_DD not in", values, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_DD between", value1, value2, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andCalendarDdNotBetween(Integer value1, Integer value2) {
            addCriterion("CALENDAR_DD not between", value1, value2, "calendarDd");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsIsNull() {
            addCriterion("WORK_START_EMBS is null");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsIsNotNull() {
            addCriterion("WORK_START_EMBS is not null");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsEqualTo(String value) {
            addCriterion("WORK_START_EMBS =", value, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsNotEqualTo(String value) {
            addCriterion("WORK_START_EMBS <>", value, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsGreaterThan(String value) {
            addCriterion("WORK_START_EMBS >", value, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_START_EMBS >=", value, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsLessThan(String value) {
            addCriterion("WORK_START_EMBS <", value, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsLessThanOrEqualTo(String value) {
            addCriterion("WORK_START_EMBS <=", value, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsLike(String value) {
            addCriterion("WORK_START_EMBS like", value, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsNotLike(String value) {
            addCriterion("WORK_START_EMBS not like", value, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsIn(List<String> values) {
            addCriterion("WORK_START_EMBS in", values, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsNotIn(List<String> values) {
            addCriterion("WORK_START_EMBS not in", values, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsBetween(String value1, String value2) {
            addCriterion("WORK_START_EMBS between", value1, value2, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartEmbsNotBetween(String value1, String value2) {
            addCriterion("WORK_START_EMBS not between", value1, value2, "workStartEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeIsNull() {
            addCriterion("WORK_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeIsNotNull() {
            addCriterion("WORK_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeEqualTo(String value) {
            addCriterion("WORK_START_TIME =", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotEqualTo(String value) {
            addCriterion("WORK_START_TIME <>", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeGreaterThan(String value) {
            addCriterion("WORK_START_TIME >", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_START_TIME >=", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeLessThan(String value) {
            addCriterion("WORK_START_TIME <", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeLessThanOrEqualTo(String value) {
            addCriterion("WORK_START_TIME <=", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeLike(String value) {
            addCriterion("WORK_START_TIME like", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotLike(String value) {
            addCriterion("WORK_START_TIME not like", value, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeIn(List<String> values) {
            addCriterion("WORK_START_TIME in", values, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotIn(List<String> values) {
            addCriterion("WORK_START_TIME not in", values, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeBetween(String value1, String value2) {
            addCriterion("WORK_START_TIME between", value1, value2, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkStartTimeNotBetween(String value1, String value2) {
            addCriterion("WORK_START_TIME not between", value1, value2, "workStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeIsNull() {
            addCriterion("CALC_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeIsNotNull() {
            addCriterion("CALC_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeEqualTo(String value) {
            addCriterion("CALC_START_TIME =", value, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeNotEqualTo(String value) {
            addCriterion("CALC_START_TIME <>", value, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeGreaterThan(String value) {
            addCriterion("CALC_START_TIME >", value, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CALC_START_TIME >=", value, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeLessThan(String value) {
            addCriterion("CALC_START_TIME <", value, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeLessThanOrEqualTo(String value) {
            addCriterion("CALC_START_TIME <=", value, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeLike(String value) {
            addCriterion("CALC_START_TIME like", value, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeNotLike(String value) {
            addCriterion("CALC_START_TIME not like", value, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeIn(List<String> values) {
            addCriterion("CALC_START_TIME in", values, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeNotIn(List<String> values) {
            addCriterion("CALC_START_TIME not in", values, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeBetween(String value1, String value2) {
            addCriterion("CALC_START_TIME between", value1, value2, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andCalcStartTimeNotBetween(String value1, String value2) {
            addCriterion("CALC_START_TIME not between", value1, value2, "calcStartTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsIsNull() {
            addCriterion("WORK_END_EMBS is null");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsIsNotNull() {
            addCriterion("WORK_END_EMBS is not null");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsEqualTo(String value) {
            addCriterion("WORK_END_EMBS =", value, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsNotEqualTo(String value) {
            addCriterion("WORK_END_EMBS <>", value, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsGreaterThan(String value) {
            addCriterion("WORK_END_EMBS >", value, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_END_EMBS >=", value, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsLessThan(String value) {
            addCriterion("WORK_END_EMBS <", value, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsLessThanOrEqualTo(String value) {
            addCriterion("WORK_END_EMBS <=", value, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsLike(String value) {
            addCriterion("WORK_END_EMBS like", value, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsNotLike(String value) {
            addCriterion("WORK_END_EMBS not like", value, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsIn(List<String> values) {
            addCriterion("WORK_END_EMBS in", values, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsNotIn(List<String> values) {
            addCriterion("WORK_END_EMBS not in", values, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsBetween(String value1, String value2) {
            addCriterion("WORK_END_EMBS between", value1, value2, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndEmbsNotBetween(String value1, String value2) {
            addCriterion("WORK_END_EMBS not between", value1, value2, "workEndEmbs");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeIsNull() {
            addCriterion("WORK_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeIsNotNull() {
            addCriterion("WORK_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeEqualTo(String value) {
            addCriterion("WORK_END_TIME =", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotEqualTo(String value) {
            addCriterion("WORK_END_TIME <>", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeGreaterThan(String value) {
            addCriterion("WORK_END_TIME >", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_END_TIME >=", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeLessThan(String value) {
            addCriterion("WORK_END_TIME <", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeLessThanOrEqualTo(String value) {
            addCriterion("WORK_END_TIME <=", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeLike(String value) {
            addCriterion("WORK_END_TIME like", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotLike(String value) {
            addCriterion("WORK_END_TIME not like", value, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeIn(List<String> values) {
            addCriterion("WORK_END_TIME in", values, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotIn(List<String> values) {
            addCriterion("WORK_END_TIME not in", values, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeBetween(String value1, String value2) {
            addCriterion("WORK_END_TIME between", value1, value2, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andWorkEndTimeNotBetween(String value1, String value2) {
            addCriterion("WORK_END_TIME not between", value1, value2, "workEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeIsNull() {
            addCriterion("CALC_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeIsNotNull() {
            addCriterion("CALC_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeEqualTo(String value) {
            addCriterion("CALC_END_TIME =", value, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeNotEqualTo(String value) {
            addCriterion("CALC_END_TIME <>", value, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeGreaterThan(String value) {
            addCriterion("CALC_END_TIME >", value, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CALC_END_TIME >=", value, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeLessThan(String value) {
            addCriterion("CALC_END_TIME <", value, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeLessThanOrEqualTo(String value) {
            addCriterion("CALC_END_TIME <=", value, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeLike(String value) {
            addCriterion("CALC_END_TIME like", value, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeNotLike(String value) {
            addCriterion("CALC_END_TIME not like", value, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeIn(List<String> values) {
            addCriterion("CALC_END_TIME in", values, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeNotIn(List<String> values) {
            addCriterion("CALC_END_TIME not in", values, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeBetween(String value1, String value2) {
            addCriterion("CALC_END_TIME between", value1, value2, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andCalcEndTimeNotBetween(String value1, String value2) {
            addCriterion("CALC_END_TIME not between", value1, value2, "calcEndTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCorrectValueIsNull() {
            addCriterion("CORRECT_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andCorrectValueIsNotNull() {
            addCriterion("CORRECT_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andCorrectValueEqualTo(Integer value) {
            addCriterion("CORRECT_VALUE =", value, "correctValue");
            return (Criteria) this;
        }

        public Criteria andCorrectValueNotEqualTo(Integer value) {
            addCriterion("CORRECT_VALUE <>", value, "correctValue");
            return (Criteria) this;
        }

        public Criteria andCorrectValueGreaterThan(Integer value) {
            addCriterion("CORRECT_VALUE >", value, "correctValue");
            return (Criteria) this;
        }

        public Criteria andCorrectValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("CORRECT_VALUE >=", value, "correctValue");
            return (Criteria) this;
        }

        public Criteria andCorrectValueLessThan(Integer value) {
            addCriterion("CORRECT_VALUE <", value, "correctValue");
            return (Criteria) this;
        }

        public Criteria andCorrectValueLessThanOrEqualTo(Integer value) {
            addCriterion("CORRECT_VALUE <=", value, "correctValue");
            return (Criteria) this;
        }

        public Criteria andCorrectValueIn(List<Integer> values) {
            addCriterion("CORRECT_VALUE in", values, "correctValue");
            return (Criteria) this;
        }

        public Criteria andCorrectValueNotIn(List<Integer> values) {
            addCriterion("CORRECT_VALUE not in", values, "correctValue");
            return (Criteria) this;
        }

        public Criteria andCorrectValueBetween(Integer value1, Integer value2) {
            addCriterion("CORRECT_VALUE between", value1, value2, "correctValue");
            return (Criteria) this;
        }

        public Criteria andCorrectValueNotBetween(Integer value1, Integer value2) {
            addCriterion("CORRECT_VALUE not between", value1, value2, "correctValue");
            return (Criteria) this;
        }

        public Criteria andWorkTimeIsNull() {
            addCriterion("WORK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andWorkTimeIsNotNull() {
            addCriterion("WORK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTimeEqualTo(Integer value) {
            addCriterion("WORK_TIME =", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeNotEqualTo(Integer value) {
            addCriterion("WORK_TIME <>", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeGreaterThan(Integer value) {
            addCriterion("WORK_TIME >", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("WORK_TIME >=", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeLessThan(Integer value) {
            addCriterion("WORK_TIME <", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeLessThanOrEqualTo(Integer value) {
            addCriterion("WORK_TIME <=", value, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeIn(List<Integer> values) {
            addCriterion("WORK_TIME in", values, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeNotIn(List<Integer> values) {
            addCriterion("WORK_TIME not in", values, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeBetween(Integer value1, Integer value2) {
            addCriterion("WORK_TIME between", value1, value2, "workTime");
            return (Criteria) this;
        }

        public Criteria andWorkTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("WORK_TIME not between", value1, value2, "workTime");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNull() {
            addCriterion("REGISTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIsNotNull() {
            addCriterion("REGISTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterIdEqualTo(String value) {
            addCriterion("REGISTER_ID =", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotEqualTo(String value) {
            addCriterion("REGISTER_ID <>", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThan(String value) {
            addCriterion("REGISTER_ID >", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID >=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThan(String value) {
            addCriterion("REGISTER_ID <", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLessThanOrEqualTo(String value) {
            addCriterion("REGISTER_ID <=", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdLike(String value) {
            addCriterion("REGISTER_ID like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotLike(String value) {
            addCriterion("REGISTER_ID not like", value, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdIn(List<String> values) {
            addCriterion("REGISTER_ID in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotIn(List<String> values) {
            addCriterion("REGISTER_ID not in", values, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdBetween(String value1, String value2) {
            addCriterion("REGISTER_ID between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterIdNotBetween(String value1, String value2) {
            addCriterion("REGISTER_ID not between", value1, value2, "registerId");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNull() {
            addCriterion("REGISTER_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIsNotNull() {
            addCriterion("REGISTER_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeEqualTo(Date value) {
            addCriterion("REGISTER_DATIME =", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <>", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThan(Date value) {
            addCriterion("REGISTER_DATIME >", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME >=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThan(Date value) {
            addCriterion("REGISTER_DATIME <", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeLessThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATIME <=", value, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeIn(List<Date> values) {
            addCriterion("REGISTER_DATIME in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotIn(List<Date> values) {
            addCriterion("REGISTER_DATIME not in", values, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andRegisterDatimeNotBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATIME not between", value1, value2, "registerDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("UPDATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("UPDATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(String value) {
            addCriterion("UPDATE_ID =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(String value) {
            addCriterion("UPDATE_ID <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(String value) {
            addCriterion("UPDATE_ID >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(String value) {
            addCriterion("UPDATE_ID <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_ID <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLike(String value) {
            addCriterion("UPDATE_ID like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotLike(String value) {
            addCriterion("UPDATE_ID not like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<String> values) {
            addCriterion("UPDATE_ID in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<String> values) {
            addCriterion("UPDATE_ID not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(String value1, String value2) {
            addCriterion("UPDATE_ID between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_ID not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNull() {
            addCriterion("UPDATE_DATIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIsNotNull() {
            addCriterion("UPDATE_DATIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeEqualTo(Date value) {
            addCriterion("UPDATE_DATIME =", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <>", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThan(Date value) {
            addCriterion("UPDATE_DATIME >", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME >=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThan(Date value) {
            addCriterion("UPDATE_DATIME <", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATIME <=", value, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeIn(List<Date> values) {
            addCriterion("UPDATE_DATIME in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotIn(List<Date> values) {
            addCriterion("UPDATE_DATIME not in", values, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME between", value1, value2, "updateDatime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATIME not between", value1, value2, "updateDatime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dt_work_time
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 13 23:34:32 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dt_work_time
     *
     * @mbg.generated Fri Apr 13 23:34:32 JST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}