package jp.co.pds.PJ0002.dao.dto;

import java.util.Date;

public class MsAccountTitle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_account_title.ACCOUNT_TITLE_ID
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    private Integer accountTitleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_account_title.ACCOUNT_TITLE_CD
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    private String accountTitleCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_account_title.ACCOUNT_TITLE_NAME
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    private String accountTitleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_account_title.REGISTER_ID
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    private String registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_account_title.REGISTER_DATIME
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    private Date registerDatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_account_title.UPDATE_ID
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_account_title.UPDATE_DATIME
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    private Date updateDatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_account_title.ACCOUNT_TITLE_ID
     *
     * @return the value of ms_account_title.ACCOUNT_TITLE_ID
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public Integer getAccountTitleId() {
        return accountTitleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_account_title.ACCOUNT_TITLE_ID
     *
     * @param accountTitleId the value for ms_account_title.ACCOUNT_TITLE_ID
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public void setAccountTitleId(Integer accountTitleId) {
        this.accountTitleId = accountTitleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_account_title.ACCOUNT_TITLE_CD
     *
     * @return the value of ms_account_title.ACCOUNT_TITLE_CD
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public String getAccountTitleCd() {
        return accountTitleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_account_title.ACCOUNT_TITLE_CD
     *
     * @param accountTitleCd the value for ms_account_title.ACCOUNT_TITLE_CD
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public void setAccountTitleCd(String accountTitleCd) {
        this.accountTitleCd = accountTitleCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_account_title.ACCOUNT_TITLE_NAME
     *
     * @return the value of ms_account_title.ACCOUNT_TITLE_NAME
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public String getAccountTitleName() {
        return accountTitleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_account_title.ACCOUNT_TITLE_NAME
     *
     * @param accountTitleName the value for ms_account_title.ACCOUNT_TITLE_NAME
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public void setAccountTitleName(String accountTitleName) {
        this.accountTitleName = accountTitleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_account_title.REGISTER_ID
     *
     * @return the value of ms_account_title.REGISTER_ID
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public String getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_account_title.REGISTER_ID
     *
     * @param registerId the value for ms_account_title.REGISTER_ID
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public void setRegisterId(String registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_account_title.REGISTER_DATIME
     *
     * @return the value of ms_account_title.REGISTER_DATIME
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public Date getRegisterDatime() {
        return registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_account_title.REGISTER_DATIME
     *
     * @param registerDatime the value for ms_account_title.REGISTER_DATIME
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public void setRegisterDatime(Date registerDatime) {
        this.registerDatime = registerDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_account_title.UPDATE_ID
     *
     * @return the value of ms_account_title.UPDATE_ID
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_account_title.UPDATE_ID
     *
     * @param updateId the value for ms_account_title.UPDATE_ID
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_account_title.UPDATE_DATIME
     *
     * @return the value of ms_account_title.UPDATE_DATIME
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public Date getUpdateDatime() {
        return updateDatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_account_title.UPDATE_DATIME
     *
     * @param updateDatime the value for ms_account_title.UPDATE_DATIME
     *
     * @mbg.generated Wed Jun 13 00:08:07 JST 2018
     */
    public void setUpdateDatime(Date updateDatime) {
        this.updateDatime = updateDatime;
    }
}